### ISSUE TITLE
Sending to all in room, including self

### ISSUE THREAD

**Issue by tomsseisums** [socketio/socket.io#1183]
I cannot seem to find a way how to emit event to all clients inside a room including self.

Basicly `socket.in('myroom').broadcast.emit()` emits to **all, except self** and `socket.in('myroom').emit()` sends **only to self**.

I know I can do both at the same time, but that doesn't feel effective to me.

How do I emit to **all clients** in the room, **including self** with one call?

**Update:**
Okay, I manged to emit to all with `io.sockets.in('myroom').emit();`, but that made me introduce `io` into global scope, that kind of ruins my decoupling.

Is there a way to do it through `socket` object?

**Comment by liesislukas** [comment]
@yads your example works well :+1:  socket.io v 1.3.7

**Comment by tsukuros** [comment]
@yads worked for me as well, thank you

**Comment by pumpkinp** [comment]
@yads good,

**Comment by chongxx** [comment]
@yads your example can works, thanks you.

**Comment by immatobi** [comment]
@yads Works well, thanks

**Comment by aldaineclarke** [comment]
@yads Nice save. 👍

**Comment by kadamato** [comment]
tks u

**Comment by kadamato** [comment]
@yads  tks u

**Comment by FurqanAnwar** [comment]
@yads Thanks mate.

**Comment by Lucas-I-Marciano** [comment]
@yads Amazing! I could find what nsp means on Socket.io. Do you know that?

**Comment by bkhebert** [comment]
> [@yads](https://github.com/yads) Amazing! I could not find what nsp means on Socket.io. Do you know that?

In my understanding for Socket.IO, nsp (namespaces) act as isolated channels for communication. When you create a new socket, it's like tuning into a radio station that broadcasts on a specific frequency. Without specifying a namespace, you're essentially broadcasting your message on a public channel where anyone can listen in, which can lead to chaos and unwanted crosstalk. But by using 'nsp', you create a private channel for your sockets to communicate on. 

Imagine a large office building with hundreds of employees. If everyone talked at once, you'd have a cacophony of noise and no one would get anything done. Now, introduce conference rooms with walls—each room is a namespace. When you use 'socket.nsp.to('room').emit(data)', you're essentially speaking into the intercom of that specific conference room. Only the sockets that have joined that 'room' namespace will receive the message. Take a step further back and look at the documentation on namespaces:

 `io.sockets === io.of("/")` <-- this is a default 'namespace' of io. Where the namespace is essentially global. So whenever I try to put two and two together; I am thinking that:
`socket.nsp === io.of('this socket')`.
in which case
`socket.nsp.emit(data)` <-- this part emits only to yourself...?

the latter half
`socket.to(room).emit` <--- behaves normally by emitting to all in the room except yourself 

then the final part is just chaining the two
`socket.nsp.to(room).emit(data) <--- emits to yourself, and to everyone else in a certain room

I am not too sure, but I am thinking about writing a dev.to article about this because it seems as if there is no official documentation explaining the .nsp property on the socket from their official site for any version whatsoever. 
-cheers
