### ISSUE TITLE
Empty rooms aren't deleted

### ISSUE THREAD

**Issue by AnotherSymbiote** [socketio/socket.io#1599]
I noticed a possible memory leak, so I tested by connecting to my server from about a dozen client webpages and repeatedly refreshing them. Memory usage increased with each refresh and never fell back to pre-refresh levels.

Turns out the unique rooms that are created for new connections aren't getting deleted — they remain in the room list despite becoming empty upon refresh. Empty rooms are supposed to be destroyed automatically, so I don't know what's going on, but it might be why memory usage keeps rising.

I tried explicitly deleting these rooms when a client disconnects. This removes them from the room list, but memory usage seems unaffected. I might be doing it wrong:

``` javascript
socket.on('disconnect', function() {
    delete io.sockets.adapter.rooms[socket.id];
});
```

Does this seem strange to anyone else? Is there another potential reason for the memory leak?

**Comment by ncacace** [comment]
My application uses randomly generated rooms. I use a variable to 'lease/reserve' rooms for a predetermined amount of time. Once the time is exceeded the room will be will be destroyed. The host is notified before this happens in case they want to extend the time.

Sometimes rooms require that data persistence be maintained if the room is destroyed. In this way if the room is regenerated at a later date the previous session's data can be repopulated. This persistent data needs to be deleted if the room is terminated.

I don't think it's right to automatically delete a room because it's not being used. I would add a switch (0,1,expiration datetimestamp), 0 being the default, when a room is created so that a pseudo garbage collector is notified whether a room should be set to null for collection by the Garbage collector.

ALSO... is the host creating a room where THEY dictate whether a room is to be destroyed once they no longer require it OR are they merely generating a room which will take on a life of its own; continuing to exist long after the host has left, as long as it is being used?

**Comment by darrachequesne** [comment]
@ncacace I think your use case is a bit too specific to be implemented in socket.io internals.

The room is destroyed once the last element leaves it (https://github.com/socketio/socket.io-adapter/blob/1.1.1/index.js#L81).
