### ISSUE TITLE
IE iframe

### ISSUE THREAD

**Issue by MeterSoft** [socketio/socket.io#1803]
I have some error in IE8
document.__IE_DEVTOOLBAR_CONSOLE_EVAL_RESULT = undefined;
error: SCRIPT70

socket v 1.1.0

**Comment by JokerQyou** [comment]
This problem is still there in compatible mode (IE 8) of IE 11 (detailed version as followed)
![image](https://cloud.githubusercontent.com/assets/1465267/5895268/4ac5a28a-a555-11e4-88d5-93e526423b2c.png)

I did nothing but connecting to a Socket.io server. The server side does nothing. In fact, I was trying to build a prototype of chatting project. 
This does not occur all the time, it seems that it occurs 1 time out of 4~8 pulling events. 

And this always comes in a couple or more. A SCRIPT70 error would occur, and report itself at the very beginning of the page (where the `<!doctype...` lays ), and follwed by another SCRIPT 70 error reporting itself at line 1 column 1 of `browsertools.library.js`, the whole file content is as followed. I think this file is something inside the IE debugging tool. 



```javascript
document.__IE_DEVTOOLBAR_CONSOLE_EVAL_RESULT = undefined;
document.__IE_DEVTOOLBAR_CONSOLE_EVAL_ERROR = false;
document.__IE_DEVTOOLBAR_CONSOLE_EVAL_ERRORCODE = undefined;
try{
document.__IE_DEVTOOLBAR_CONSOLE_EVAL_RESULT = eval("(function () { })();\r\n//# sourceURL=browsertools://browsertools.console.js");
}
catch( eObj ){
document.__IE_DEVTOOLBAR_CONSOLE_EVAL_ERRORCODE = eObj.number;
document.__IE_DEVTOOLBAR_CONSOLE_EVAL_RESULT = eObj.message || eObj.description || eObj.toString();
document.__IE_DEVTOOLBAR_CONSOLE_EVAL_ERROR = true;
}
```

**Comment by liujiasheng** [comment]
@JokerQyou my situation is almost the same as yours

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
