### ISSUE TITLE
AWS EC2 Behind ELB Always Prints Error Unexpected response code: 400

### ISSUE THREAD

**Issue by framerate** [socketio/socket.io#1846]
Hey guys -

Can't seem to find out a solution for this, but when I run my app behind a load balancer, I get this error on the client:

```
WebSocket connection to 'wss://fakedomain.com/socket.io/?EIO=3&transport=websocket&sid=QH8VmXbiEcp3ZyiLAAAD' failed: Error during WebSocket handshake: Unexpected response code: 400 
```

I understand the error, since it's trying to talk to the load balancer and now the EC2 instance (I'm not great with AWS so feel free to offer help on this one!) but what I don't understand is how to make the error not show up!

I'd love to fix the root cause but I'm guessing it involves a separate dedicated socket.io server to handle all the real time stuff which I don't have time for at the moment, but could someone please run me through supressing this error?

I'm assuming it's falling back to polling, which seems to work just fine (I have the socket connection connected and it fires) but I don't want to launch with a red error in my console. 

Thanks in advance for any advice you might have!

**Comment by aidanbon** [comment]
Thanks @niczak !!

I finally got mine working as well. However, in additional to configuring 
1) Load balancer to use TCP protocol
2) Load balancer to disable Cross-Zone load balancing

I also need to set
3) Proxy server to be "none" in the Software Configuration section.

![screen shot 2015-01-09 at 10 28 56 am](https://cloud.githubusercontent.com/assets/2024333/5685008/330b770e-97eb-11e4-87fd-155e19f0bbe3.png)

**Comment by niczak** [comment]
That's great news @aidanbon and @petrogad, huzzah for sockets on AWS! :+1:

**Comment by PuKoren** [comment]
Thanks a lot! It solved my issue with elastic beanstalk. It makes sense to remove nginx proxy

**Comment by framerate** [comment]
AN update from my original post:

I have my HTTPS changed to SSL (443 ---> my custom port) and left HTTP (80 ---> my custom port).

I have code that was checking with express !req.secure && X-Forwarded-Proto !=== https that redirects you to HTTPS if you come in on port 80...

HOWEVER

Changing to SSL makes X-Forwarded-Proto come back undefined.... breaking this connection. (also req.secure seems like it may be deprecated)

So now:

```
if (req.get('X-Forwarded-Proto') === 'http') {
            res.redirect('https://' + req.get('Host') + req.url);
        }
```

seems to work great, and I don't get the 400 error in the console any more.

**Comment by ChrisEdson** [comment]
Hullo - I got this working using Node, NGINX, SSL, and an ELB on Elastic Beanstalk doing the following:

Create a container command in .ebextensions to modify the nginx configuration script to include proxy websockets:
```
container_commands:
    00proxy:
        command: sed -i 's/proxy_http_version.*/proxy_http_version\ 1.1\;\n\ \ \ \ \ \ \ \ proxy_set_header\ \ \ \ \ \ \ \ Upgrade\ \ \ \ \ \ \ \ \ \$http_upgrade\;\n\ \ \ \ \ \ \ \ proxy_set_header\ \ \ \ \ \ \ \ Connection\ \ \ \ \ \ \"upgrade\"\;/g' /tmp/deployment/config/#etc#nginx#conf.d#00_elastic_beanstalk_proxy.conf
```

Install your SSL cert on the load balancer using the Elastic Beanstalk web console.

Then go to the EC2 web console, and change the load balancer to listen on SSL 443 -> TCP 80. This did not working when I changed it in the EB web console, I had to do it directly in EC2.

That should get everything working. I haven't had to do any redirects and I managed to get NGINX working too.

**Comment by Treyone** [comment]
@ChrisEdson is there anything else to include in the package to use this solution ?
I gave it a try but the deployment failed due to errors. The log show the follofing line : 
```
/etc/init.conf: Unable to load configuration: No such file or directory
```

**Comment by ChrisEdson** [comment]
Can you post your code?



—
Chris Edson
+44 7732 480747

**Comment by Treyone** [comment]
The app code is an extremely basic socket.io imprementation, almost an out of the box example usage.
The only thing I added is the .config file in .ebextensions, in which I copied the code snippet you quoted earlier.
So I don't have much to post :)

**Comment by ChrisEdson** [comment]
No worry, it's just difficult to debug without the code or logs. Can you post the logs? Probably not appropriate to stick up on here, maybe put them in a paste bin. 



—
Chris Edson
+44 7732 480747

**Comment by Treyone** [comment]
Hum, I published my code via grunt instead of a manual packaging and it works like a charm. Automatization should be mandatory ;)

**Comment by ChrisEdson** [comment]
Glad to hear it!


—
Chris Edson
+44 7732 480747

**Comment by tarkus** [comment]
Save my day!

**Comment by lostcolony** [comment]
We saw this basic issue, too. Basically, because SocketIO sends two requests to establish the websocket connection, if those calls get federated across instances, the session ID is not recognized and the handshake fails, leading to SocketIO falling back to long polling. This is true whether or not you're using ws or wss; it assumes you've set up load balancing at layer-4 (TCP), as I could not get layer-7 (HTTP) load balancing to work with websockets.

The fix would be to enable sticky sessions, so that once a call goes across to an instance, the load balancer continues to send those requests to the same instance; however, if you're using AWS' ELBs, they do not allow you to use sticky sessions for layer-4 load balancing.

What we ended up doing was using raw websockets, as then there is no session data that needed to be persisted across calls (just one call, the handshake, takes place, and that works). It may be possible to persist the sessionID across instances with redis or similar and have it resolved that way for SocketIO to work, but I haven't tried it.

A fix on AWS' part would be to allow sticky sessions to be used in some manner for layer-4 load balancing.

A fix on SocketIO's part would be to make it so the websocket handshake does not require the context of the sessionID.

**Comment by sahanDissanayake** [comment]
@aidanbon I could not find ``Proxy server to be "none" in the Software Configuration section`` ? 

I'm simply using a ubuntu server and MeteorJS with mup deployment.. could you please get me a link ??

Cheers

**Comment by aidanbon** [comment]
@sahanDissanayake  I found my Proxy Server config option via:
1. Click "Configuration" at the Environment of interest
2. Click "Software Configuration" from within the Configuration page
3. The "Proxy server" drop-down as shown in my previous screenshot.

Note: My environment was provisioned almost a year ago. Not sure AWS panel has updated for newer environments. However, I can still see this drop-down today at my environment.

**Comment by sahanDissanayake** [comment]
@aidanbon I do not use any other services other that ec2.. so your settings is not relavant to me ? or do i  need to start using this poxy server ?

**Comment by sahanDissanayake** [comment]
@yoav200 I did exactly what you explained.. did not work.. any thoughts ?? http://ec2-52-90-105-212.compute-1.amazonaws.com/

**Comment by sahanDissanayake** [comment]
So the issue I have is, my web app websockets work in port 8080, but NOT in port 80.

This is the issue

**Comment by felixSchl** [comment]
@lostcolony Thank you for the summary. I have arrived at the same conclusion. Have you read this blog post: https://medium.com/@Philmod/load-balancing-websockets-on-ec2-1da94584a5e9#.hd2ectz8t? He's essentially saying one could pass the layer-4 (TCP) through to a HAProxy instance, which then takes off the PROXY header and routes the traffic to the right instance using sticky sessions. However, it is not apparent to me how the two HAProxy get their "backend" server list configured and where it runs and where the actual socket.io server runs. Can you make any sense of it?

**Comment by lostcolony** [comment]
The server list would be configured on each HAproxy box. I'm not sure how
to make that work with auto scaling ec2 instances, unless you wrote some
additional infrastructure to update that list when a new server came
online. Socket.io they're running on the same server as their Web app, so
connections come in through the Elb, are federated to an HAproxy instance,
the HAproxy instance(s) ensure that IPs connections always go to the same
web/app server, which is where socket.io was set up.

**Comment by felixSchl** [comment]
@lostcolony OK, I saw there was a interesting project in regards to auto-scaling on amazon, using HAProxy - at least useful for reference: https://github.com/markcaudill/haproxy-autoscale. What I don't get is why use an ELB in front of HAProxy? There must be only one HAProxy instance, otherwise, how would you guarantee that the ELB sends traffic to the right HAProxy instance? Unless they (the HAProxy instances) shared a common sticky table somehow using ElastiCache or Redis or something along those lines? ... I do realize we are going _way_ off topic.

**Comment by lostcolony** [comment]
If you have the HAProxies configured to route connections based on IP you
could guarantee it'd end up at the same instance. That is, if the HAProxies
all had the same rule saying that ip A.B.C.D is directed to instance one,
then regardless of which HAProxy the ELB hit, it would end up at the same
place. That's what is happening in that link you sent, they're balancing
via source, meaning the HAProxy instance hashes the IP and uses that to
determine what instance it goes to. Multiple HAProxies, provided they all
know about the same instances, would thus send traffic from one location to
the same backend instance.

**Comment by felixSchl** [comment]
@lostcolony I understand that the hash is derived deterministically for a given ip, however, there must be a mapping of "hash -> instance". In your case you are saying there is a rule that's saying "A.B.C.D is directed to instance one", but would you not want HAProxy to determine itself where to redirect to, given a list of available servers? After all, "A.B.C.D" is just some client's ip and not known up front.

**Comment by lostcolony** [comment]
The rule for mapping the hash to an instance is the same across all HAProxy
instances. That is, A.B.C.D will result in the same hash no matter the
HAProxy instance it hits, and that hash will map to the same server, no
matter the HAProxy instance in use, provided that every HAProxy knows about
the same instances (and possibly in the same order/the same names). The
actual IPs do not have to be known up front, because they're immaterial.
Any IP will hash to the same server regardless of the HAProxy it passes
through.

For a completely faked example (HAProxy uses something that is not so
predictable, I'm sure), imagine we had three servers, which are configured
in order as server0, server1, and serve2 (the actual details don't matter,
just that there is a clear ordering, implicit is fine). Every HAProxy
instance has the same servers, in the same order. They also have the same
rule as to how to deal with an incoming IP address. For this trite example,
it's add up all four parts of the address as integers (easily extensible to
support IPv6, add up all as hex into base 10), and divide by 3, take the
remainder. So IP 123.12.61.24 = (123+12+61+24) % 3, or 1. So it gets routed
to server1. So no matter what HAProxy instance it comes into, that
connection will be sent to server1.

Now, if server1 goes offline, the algorithm changes across all HAProxy
instances, to being add all the parts, modulus 2.

And this generally works -unless- you get a netsplit (or configure the
HAProxy instances to have a different server list). Where one HAProxy sees
3 instances, and another sees 2. If that happens, you can't be guaranteed
to reach the same backend. And indeed, that can prove to be a problem. But
that's the solution being described in the link.

**Comment by williamcoates** [comment]
I found that on Elastic Beanstalk even though i had setup the Load balancer to use TCP and SSL with the web interface, when I checked the load balancer config directly it was still using HTTPS for the secure listener. So you should probably check in the EC2 > Load Balancers section that the ports are setup as they should be: 

<img width="596" alt="screen shot 2016-03-08 at 16 08 34" src="https://cloud.githubusercontent.com/assets/50446/13607437/0e71c780-e548-11e5-9f6c-f92940684231.png">

Once that is sorted add the following to .ebextensions and all works well for me :)

```
container_commands:
  01_nginx_static:
    command: |
      sed -i '/\s*proxy_set_header\s*Connection/c \
              proxy_set_header Upgrade $http_upgrade;\
              proxy_set_header Connection "upgrade";\
          ' /tmp/deployment/config/#etc#nginx#conf.d#00_elastic_beanstalk_proxy.conf

```
This will only work 100% when you only have one instance however, because sticky session support doesnt work over TCP.

**Comment by felixSchl** [comment]
@lostcolony, @williamcoates post just now reminded me to thank you for explanation. Cannot believe I forgot to do that. Your explanation was tremendously helpful, so thank you for taking the time.

**Comment by Mad-Head** [comment]
https://github.com/indutny/sticky-session/issues/47#issuecomment-227499752

**Comment by Mad-Head** [comment]
https://github.com/indutny/sticky-session/issues/47#issuecomment-227499752

**Comment by xorq** [comment]
So I had the same problem and turned out it I had set up the ECB to use HTTPS.
I changed HTTPS to SSL and I dont get the message anymore.
so, just don't use HTTP/HTTPS but TCP/SSL

**Comment by trans1t** [comment]
As of Aug 2016 you can use Amazon's Application Load Balancer (ALB) instead of the "classic" ELB.  Worked "out of the box" for me with listeners on HTTP 80 and HTTPS 443.

**Comment by niczak** [comment]
@trans1t Sweet man, thanks for the info! I will have to check that out.

**Comment by aidanbon** [comment]
@niczak - I also has switched to ALB for socket traffic stickiness. However, I first struggled with the ALB Sticky Sessions configuration (as there weren't too much doc on this subject; at least a few months ago). Finally have it figured out. The key thing is that "Stickiness is defined at a target group level", so make sure you create target group to serve your traffic and then add stickiness to it.

**Comment by niczak** [comment]
@aidanbon That is fantastic information, thank you so much for sharing!

**Comment by michaelmitchell** [comment]
For anyone that is still having a problem with AWS Application Load Balancer try updating your Security Policy, I ran into the same problem even though it was working perfectly fine in the exact setup for another website but noticed the security policy was about 1 year behind. Updating it to a newer one seems to have solved the problem.

**Comment by Treyone** [comment]
@michaelmitchell did you change anything, or just update it without modification ?

**Comment by michaelmitchell** [comment]
I didn't change anything in my application, the only additional step I did take was to remove and re-add the HTTPS listener on the ALB as after changing to the new policy didn't appear to work.

I did learn however that seeing the error even after updating the security policy was likely my browser session holding onto the old security policy so I am not sure if adding/re-adding the listener was really needed, but opening incognito it worked fine and after closing all my chrome sessions and reopening it worked fine and haven't seen it since.

**Comment by Treyone** [comment]
Good to know, thanks !

Le ven. 31 mars 2017 à 12:02, Michael Mitchell <notifications@github.com> a
écrit :

**Comment by anderoonies** [comment]
It seems like this thread became a place for figuring out issues with AWS/socket.io—

My setup is that the client makes an HTTPS request with data for a socket.io connection.
In theory, the first HTTPS request should set up the cookies needed for sticky sessions.

I'm using an ALB with these listeners:
![image](https://user-images.githubusercontent.com/6645121/43966734-a7bdd31e-9c90-11e8-83c6-0cd6ada1bece.png)

Which points to a target group with stickiness configured like this:
![image](https://user-images.githubusercontent.com/6645121/43966624-601b75c0-9c90-11e8-9738-69e9fcbf057e.png)

I hit the HTTPS endpoint first with:
```js
fetch(`https://${url}/hub/api/spinup/${uuid}`, {
                method: 'GET',
                headers: headers,
            })
```
then initialize the socket with
```js
connection = io(`wss://${url}:443/`, {
            path: `/user/${uuid}/spawn`,
        })
```

The instance the HTTPS request hits _must_ be the instance the socket connection hits.

Once a socket is established (if it hits the right instance by dumb luck) it stays there and things work well, the issue is getting the websocket to hit the same endpoint as the HTTPS request.

Has anyone done something similar?

**Comment by lostcolony** [comment]
I haven't done similar, but, while ALBs still don't have header based routing, they -do- have host based routing. This is extremely hackish, as such, but you could basically make it so that each instance behind the ALB has an explicit path to it, that the instance knows about. When that initial HTTP request goes out, part of the response includes the path, and the connection for the websocket includes that path. I.e., the HTTP request hits instance '5' (based on whatever criteria; generated UUIDs would be better), returns '5' as part of the response, and the websocket is opened to url/5. The ALB has a rule that url/5 gets routed to instance 5.

If you're using autoscaling (and your instances are cattle not pets), you'll need to have your code running on the instance modify the ALB settings to route the appropriate domain to it.

Read more here: https://aws.amazon.com/blogs/aws/new-host-based-routing-support-for-aws-application-load-balancers/

**Comment by lostcolony** [comment]
I will also say, however, that you probably want to just avoid the pattern you're using if at all possible. The data coming in the HTTP request should be stored in a way that is accessible to every instance (DB or similar), or it should be part of the websocket connection. As it is, you could still have an instance die in between the HTTP request and the websocket opening up, and you could run into the same issue (albeit far less often)

**Comment by anderoonies** [comment]
@lostcolony thanks for the advice—that’s definitely worth trying. 

the http request is what triggers the websocket server be spun up (it’s actually in a docker container, but that’s abstracted away). the two requests need to be routed to the same instance so the websocket server exists on the instance that’s being connected to

**Comment by dynofu** [comment]
with this line, it helps to sit the jupyter server behind the elb.
```
service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
```
in case somebody come to this ticket with kubernetes on aws.

**Comment by tsq** [comment]
I just disable the `HTTP2` then it's OK for me. You don't have to do anything else about ELB.

<img width="1413" alt="Screen Shot 2019-12-13 at 16 12 49" src="https://user-images.githubusercontent.com/6081537/70777621-9db5ff80-1dc3-11ea-82a9-1a916dfd2f6f.png">

**Comment by tirujack** [comment]
> Hi,
> I have the same problem, though i'm using SockJS.
> my application is a Java Spring 4 application, works on development machine and
> getting the same error on AWS.
> looks like the Upgrade header is being dropped by someone, i can see it on the client.
> 
> could find a solution yet...

Hi @yoav200 ,

SAVE ME.
I am stuck in same problem. Please help
I am using Springboot 2.x and SockJs for websocket
I have created tomcat application deployed in aws, 
 Elastic beanstalk with classic load balancer

Now the problem is 
iOS developer is unable to connect  , it reaches my backend but it fails during handshake 
 below is the logs which i get  in both CLB and ALB
---------------------
2019-12-13 15:21:22.662 DEBUG 27543 --- [nio-8080-exec-2] o.s.w.s.DispatcherServlet                : GET "/wtchat/websocket", parameters={}
2019-12-13 15:21:22.701 DEBUG 27543 --- [nio-8080-exec-2] o.s.w.s.s.s.WebSocketHandlerMapping      : Mapped to org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler@30c6a17
2019-12-13 15:21:22.714 DEBUG 27543 --- [nio-8080-exec-2] o.s.w.s.s.t.h.DefaultSockJsService       : Processing transport request: GET http://appbackend.whadatime.net/wtchat/websocket
2019-12-13 15:21:22.716 ERROR 27543 --- [nio-8080-exec-2] c.w.c.MyHandshakeHandler                 : Handshake failed due to invalid Upgrade header: null
2019-12-13 15:21:22.717 DEBUG 27543 --- [nio-8080-exec-2] o.s.w.s.DispatcherServlet                : Completed 400 BAD_REQUEST
-----------------------

I have followed what you have said
![image](https://user-images.githubusercontent.com/21166502/70854079-bf56da00-1edc-11ea-8ac9-556737fe5d47.png)
![image](https://user-images.githubusercontent.com/21166502/70854089-e4e3e380-1edc-11ea-80dd-9f43508d4c80.png)

created a record set in Route 53 which directly points to load balancer.

After doing this also I am getting same as above error.

What else do i need to do?

**Comment by tirujack** [comment]
> Hi,
> I have the same problem, though i'm using SockJS.
> my application is a Java Spring 4 application, works on development machine and
> getting the same error on AWS.
> looks like the Upgrade header is being dropped by someone, i can see it on the client.
> 
> could find a solution yet...

Hi @yoav200 ,

SAVE ME.
I am stuck in same problem. Please help
I am using Springboot 2.x and SockJs for websocket
I have created tomcat application deployed in aws, 
 Elastic beanstalk with classic load balancer

Now the problem is 
iOS developer is unable to connect  , it reaches my backend but it fails during handshake 
 below is the logs which i get  in both CLB and ALB

-------------------
2019-12-13 15:21:22.662 DEBUG 27543 --- [nio-8080-exec-2] o.s.w.s.DispatcherServlet                : GET "/wtchat/websocket", parameters={}
2019-12-13 15:21:22.701 DEBUG 27543 --- [nio-8080-exec-2] o.s.w.s.s.s.WebSocketHandlerMapping      : Mapped to org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler@30c6a17
2019-12-13 15:21:22.714 DEBUG 27543 --- [nio-8080-exec-2] o.s.w.s.s.t.h.DefaultSockJsService       : Processing transport request: GET http://mydomain.com/wtchat/websocket
2019-12-13 15:21:22.716 ERROR 27543 --- [nio-8080-exec-2] c.w.c.MyHandshakeHandler                 : Handshake failed due to invalid Upgrade header: null
2019-12-13 15:21:22.717 DEBUG 27543 --- [nio-8080-exec-2] o.s.w.s.DispatcherServlet                : Completed 400 BAD_REQUEST
-----------------------

I have followed what you have said
![image](https://user-images.githubusercontent.com/21166502/70854079-bf56da00-1edc-11ea-8ac9-556737fe5d47.png)
![image](https://user-images.githubusercontent.com/21166502/70854089-e4e3e380-1edc-11ea-80dd-9f43508d4c80.png)

created a record set in Route 53 which directly points to load balancer.

After doing this also I am getting same as above error.

What else do i need to do?

**Comment by radinmoradi** [comment]
در تاریخ یکشنبه ۱۵ دسامبر ۲۰۱۹،‏ ۰:۰۳ Tirupati Singh <
notifications@github.com> نوشت:
