### ISSUE TITLE
client can connect to non-existing namespaces and takes server resources

### ISSUE THREAD

**Issue by ofirzh** [socketio/socket.io#1867]
client can connect to non-existing namespaces and takes server resources.
unwanted connections should be dropped.
Thanks,
Ofir

**Comment by ofirzh** [comment]
"socket.io": "1.2.0"

**Comment by mahmalsami** [comment]
Is somebody still dealing with this issue ?

i'm using the 1.3.5 version, and on: 
io("http://localhost:9000/whatever-name");

still, the server is actually opening a connexion. Any solution ?
Client Side, I don't get any 'connect_failed' nor 'disconnect' event.

if i understand this MR https://github.com/Automattic/socket.io/pull/1688, the expected behavior is to disconnect the client.

**Comment by mfchung** [comment]
1.3.6, issue still exists

**Comment by Haocen** [comment]
Temporary fix without modifying Socket.io behavior:
```
socketIo.use((socket, next) => {
    setTimeout(() => {
      const namespaces = Object.keys(socket.client.nsps);
      if (namespaces.length === 1) {
        socket.disconnect();
        logger.warn(`Forbidden: ${socket.request.connection.remoteAddress} connected to root namespace only.`);
      }
      else {
        Object.keys(socket.client.nsps).filter(namespace => namespace !== '/').forEach((namespace) => {
          if (!['/namespaceA', '/namespaceB'].includes(namespace)) {
            socket.disconnect();
            logger.warn(`Forbidden: ${socket.request.connection.remoteAddress} connected to non-exist namespace.`);
          }
        });
      }
    }, 15000);
    next();
  });
```

**Comment by kuige** [comment]
2.3.0, issue still exists

**Comment by giovanni-bertoncelli** [comment]
Still existing

**Comment by giovanni-bertoncelli** [comment]
I don't think @Haocen will work anymore since `io.use` is now an alias for `io.of('/').use`. The only thing that comes in mind is a global middleware with `io.engine.use((req, res, next) => {})` but is there any way to check the requested namespace in the `req` object?

I think that this bug can bring to a useless waste of resources on the server, and event potential security issues. This should be reopened @darrachequesne. Shouldn't be clients able to connect only on server already declared namespaces?

**Comment by darrachequesne** [comment]
@giovanni-bertoncelli

> Shouldn't be clients able to connect only on server already declared namespaces?

That's the case. Are you experiencing a different behavior?

Regarding the initial issue, there is now a process that automatically disconnect clients that have not joined a namespace (https://github.com/socketio/socket.io/commit/91cd255ba76ff6a780c62740f9f5cd3a76f5d7c7), added in version `3.0.0`.

**Comment by giovanni-bertoncelli** [comment]
I can try to reproduce it

**Comment by giovanni-bertoncelli** [comment]
Nope, my bad. Not able to reproduce it anymore.

**Comment by darrachequesne** [comment]
@giovanni-bertoncelli OK, thanks a lot for taking the time to look into this. If you ever find something, please ping me!

**Comment by ofirzh** [comment]
Nice, thanks for quick resolution (from 2014😄😄 )
