### ISSUE TITLE
Loadtest using jmeter howto connect to namespace

### ISSUE THREAD

**Issue by marcofranssen** [socketio/socket.io#1894]
I'm trying to loadtest my solution using jmeter. Since I use namespaces I need to know how I can connect to the specific namespace in order to send my messages.

I have been using google chrome devtools in order to figure out how the connection to a specific namespace is established, but somehow I can't find it.

Our loadtest currently fails as soon as we try to emit on a namespace.
On the server I can see the code for the namespace is never executed, which means we actually never connect.

Does anybody know how to connect to the namespace using httprequest or websocket?
Or is this completely handled in the javascript, which makes this actually completely untestable?

**Comment by bjoshuanoah** [comment]
I'm not entirely sure what you mean by `Simply send 40/namespacename`

Is this in the path? If it's the path does should it be `/40/namespace`?

I'm just not entirely sure what you mean by sending `5` either. I realize this is what is necessary for the `socket upgrade`. just not sure how you're sending it.

**Comment by bjoshuanoah** [comment]
OK, after reverse engineering socket.io(v0.9.17), here are the steps to connect:

1: connect to socket in order to get an Socket ID:
`sampler`: HTTP sampler
`method`: get
`path`: /socket.io/1/websocket
2: use a Regular Expression Extractor post processor
`field`: Body
`Reference Name`: socketId
`Regular Expression`: (.+?):60:60:
`template`: $1$
`match num`: $1$
3: upgrade to socket using the socketId variable we just created with any params your server expects
`sampler`: websocket sampler
`path`: /socket.io/1/websocket/${socketId} 
`streaming connection`: true
4: connect to a `namespace`(optional)
`sampler`: websocket sampler
`Request Data`: 1::/path/to/namespace
5: send payload to server
`sampler`: websocket sampler
`request data`: 5::/path/to/namespace:{"name":"tacos","args":["cheese", "salsa", "carne asada"]}
6: ping server to keep connection alive
`sampler`: websocket sampler
`request data`: 2::probe

If you are looping this multiple times, make sure to put the connect to namespace in a `once only` logic controller, otherwise, it will cause your server to send responses multiple times.

**Comment by Raul666** [comment]
Hi bjoshuanoah ,
I was using the steps same what you just mentioned. My http requets is going fine an di am able to retrieve the id. but the connection is not made. and i get the following error.
[Execution Flow]
 - Opening new connection
 - Using response message pattern ".*"
 - Using disconnect pattern ""
 - Waiting for the server connection for 5000 MILLISECONDS
 - Cannot connect to the remote server


[Variables]
 - Message count: 0


[Problems]
 - Unexpected error: null
JMeter.plugins.functional.samplers.websocket.ServiceSocket.sendMessage(ServiceSocket.java:156)
JMeter.plugins.functional.samplers.websocket.WebSocketSampler.sample(WebSocketSampler.java:136)
org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
java.lang.Thread.run(Unknown Source)


Response headers:


SampleResult fields:
ContentType: 
DataEncoding: UTF-8

**Comment by Raul666** [comment]
Alls well that ends well. I figured out every puzzel and its working for me. created a test with the plugin and all errors are not gone. sending 3 requests and in between 1 ping lifesign request to keep the connection alive.

**Comment by Gnop** [comment]
Hello bjoshuanoah ,

I need to know about send payload to server.
I sent request data 2probe , it response 3probe
Now , 
I tried to sent event , but not response
Do you have example other than 5::/path/to/namespace:{"name":"tacos","args":["cheese", "salsa", "carne asada"]}

Thank you
