### ISSUE TITLE
how to set status code for socket io Authentication error

### ISSUE THREAD

**Issue by lonso** [socketio/socket.io#1916]
i use socket.io to Authentication.
if error, i throw next(new Error('Authentication error'));
but response status code is 200 not 403.
how to set it to 403?

thks.

**Comment by purpleD17** [comment]
Not sure if anyone would see this, but I would love this feature. We are trying reject clients per certain authorization logic.

``` 
  socket.disconnect();
  next(new Error());
```

works for us, but the problem is it causes our reverse proxy that points to our websocket app to just log a 502. This is not a valid 502 and is causing false positives in the logs/monitoring. We'd like to return with a 400 or 401 to avoid this "false" 502 upstream from the node server. Thanks.

Right now FYI to get this it looks like i'm going to have to respond by intercepting all http requests that are bad with a 400 before we get to socket.io, which is messier then using this middleware.

**Comment by SharkFourSix** [comment]
Bump.

@purpleD17 You could send a special termination message like `next(new Error('authentication_failed'))` and then do `setTimeout(()=>{ socket.disconnect(true); }, 3000);` to avoid packet overlap which might be causing your connections to drop.

On the client side, have your client disconnect as you get the error message. The reason you close the connection on the server as well is to guarantee that the connection does really get disconnected as soon as possible.
