### ISSUE TITLE
socket.io wiki

### ISSUE THREAD

**Issue by emilymcafee** [socketio/socket.io#2020]
Has Automattic/socket.io Wiki been moved? I have several old links that now just redirect to the main repo. The wiki was very useful to me in the past and I'd love to find it!

**Comment by dsalcedo** [comment]
Here.
http://socket.io/docs/

**Comment by donniereese** [comment]
I feel like http://sockets.io/docs/ is incomplete.  I've found it very difficult to answer many questions that I've had about how to go about using different features or how to access certain information in the best way and the docs page is very slim on information.  Also, due to this, there is a lot of outdated and faulty information being posted on other help sites simply because sockets.io doesn't have the information needed.

Is there any plan to add to the docs page or build a more complete and expansive api documentation as is with most libraries?  This would be truly helpful and appreciated.

**Comment by rauchg** [comment]
Yes. We're actively working on revamping the doc site. That said, what particular question(s) would you like answered?

**Comment by peteruithoven** [comment]
- There are a couple of options objects you can give to methods like socket.io-client' `IO()` / `Manager()` methods, socket.io's `Server()`. What options can be given and what do they mean. Things like `autoConnect`, `forceNew`, `pingInterval` are not documented at the moment. 
- I miss documentation about the different `transports` option and that system in general. 
  - What options are there? How do they work? 
  - How does it first connect and then upgrades? 
  - How can I limit a client to certain transports?
- What happens when a connection falls away?
- Socket.io middleware, and maybe on authentication specifically.
- How should I work with url parameters (some people currently try to pass a query obj to the options obj)
- Link to / summarize the following docs:
  - https://github.com/automattic/socket.io-protocol
  - https://github.com/Automattic/engine.io-client
  - https://github.com/Automattic/engine.io

I'd like to help out with this, but currently I have no clue how I can contribute to the docs. Maybe sharing how the community can contribute would be useful.

**Comment by mrgamer** [comment]
I feel the pain in this issue, there was quite some documentation in the wiki page.  
Maybe it got removed to be sure `0.9x` code examples were cleaned up.  

I see no drawbacks in re-opening wiki(s) in the repositories.
The documentation at the moment is scarce (as @peteruithoven underlined), `1.x` has been released almost a year ago, and user-made wiki could be a palliative until the website has enough documentation to make wiki(s) useless

**Comment by PedroDank** [comment]
+1 on a proper detailed wiki or user-made wiki.

**Comment by li-cn** [comment]
+1 on user-made wiki. The documentation is especially sparse for newcomers.

**Comment by alejonext** [comment]
+1

**Comment by alejonext** [comment]
I created a [repo](https://github.com/alejonext/doc-socketio), to view all options that has socket.io

**Comment by axelpale** [comment]
+1 on documentation improvement. Major issue for Socket.io growth. For example in some cases, precious info can be found from [github.com/Automattic/socket.io](https://github.com/Automattic/socket.io). In some others, from [socket.io/docs/](http://socket.io/docs/) only, such as [volatile messages](http://socket.io/docs/). Furthermore, as pointed out also by previous comments, docs are still insufficient and the behavior has to be digged out elsewhere, like is the situation with [socket.connection](http://stackoverflow.com/a/16518983/638546).

**Comment by tienthanh8490** [comment]
+1 . I'm new to socket.io and I find the documentation super behind the code too.
If you guys don't have time to make a proper doc, it's ok to just have a public doc repo so that user can contribute.

**Comment by tomoat** [comment]
io.set('log level', 1);
//Option log level is not valid. Please refer to the README.

this can't use ?

**Comment by DrPaulBrewer** [comment]
[Stackoverflow: Socket IO WebSocket requests blocked by corporate firewalls](http://stackoverflow.com/questions/18852213/socket-io-websocket-requests-blocked-by-corporate-firewalls#) linked the old wiki in [this answer](http://stackoverflow.com/a/18855820/103081) that I just edited to keep the next person from wasting time looking for something that's 404 and probably obsolete by now anyway.

That SO Q&A was the top result when googling "is websocket commonly blocked by corporate firewalls?".

Perhaps when time permits, someone could provide an updated answer.

**Comment by Ethefor** [comment]
Documentation is still incomplete... Does somebody know, where can I find information about client API details as **forceNew**, **autoConnect** and **query**?

**Comment by alejonext** [comment]
@Ethefor This is the doc => https://github.com/alejonext/doc-socketio

**Comment by darrachequesne** [comment]
For future readers: the documentation was indeed severely lacking, and is in the process of being improved/completed.

Please ping me if you see a subject that is not covered in the documentation here: https://socket.io/docs/v3/

The source for the website is here: https://github.com/socketio/socket.io-website

Thanks!
