### ISSUE TITLE
Scaling socket.io with recluster

### ISSUE THREAD

**Issue by Ajaxy** [socketio/socket.io#2231]
Hello.

I was building my app using `socket.io` with `emitter` and `redis` adapter.
I have this kind of setup:

``` javascript
var http = require('http'),
    express = require('express'),
    io = require('socket.io'),
    ior = require('socket.io-redis'),
    ioe = require('socket.io-emitter');

var redisAddr = '127.0.0.1:6379',
    app = express(),
    server = http.Server(app),
    ioServer = io(server),
    ioRedis = ior(redisAddr),
    ioEmitter = ioe(redisAddr);

ioServer.adapter(ioRedis);
ioServer.use(handshake);
ioServer.on('connection', function (socket) {
    socket.join('user#1');
    ioEmitter.to('user#2').emit('hello');
});
```

But when I started using [`recluster`](https://github.com/doxout/recluster) (that simply clones nodes to sub-workers on the same machine) I faced problems.

\1. Loosing session data. After connection client script continues requesting server (I have no idea, why) with GET and POST **transport=polling** requests:

> http://localhost:3001/socket.io/?&EIO=3&transport=polling&t=1441798261383-24&sid=7Oe3jWThw3FWLy_7AAAA .

And sometimes it gets `400 Bad Request` with this JSON response: `{"code":1,"message":"Session ID unknown"}`. Does anyone knows, how to handle this? Probably I need kind of sticky session in recluster.

\2. Sometimes (even if connection is okay) this error:

> `WebSocket connection to 'ws://localhost:3001/socket.io/?EIO=3&transport=websocket&sid=qMfrVbYewG2Q4_DgAAAC' failed: Connection closed before receiving a handshake response`

appears in Chrome Web Tools console.

\3. Are rooms scaled? Before sending any socket message to a user, I check if it's still connected using this code:

``` javascript
function isOnline (userId) {
    var room = ioServer.sockets.adapter.rooms['user#' + userId];
    return room ? Object.keys(room).length > 0 : false;
}
```

But this code seems to check only users, connected by current worker, ignoring that user may be connected in another worker. What am I doing wrong here?

Big thanks in advance.

**Comment by gvilarino** [comment]
I had the same scenario (socket.io-dependent app, need to scale to multicore machines) and I ended up using [`sticky-session`](https://github.com/indutny/sticky-session) which relies on `node`'s native [`cluster`](https://nodejs.org/docs/latest-v0.12.x/api/cluster.html) (it's `unstable` under `0.12` but `stable` under `4.0`; but I have't experienced any problem under `0.12`)

It just worked almost auto-magically for me. If you want to dive deeper into what `sticky-session` does I can recommend [this repo](https://github.com/elad/node-cluster-socket.io)

**Comment by Ajaxy** [comment]
@gvilarino, thank you. So, you managed it to work without `node-cluster-socket.io`? Just `sticky-session` was enough?

By the way the third question about rooms lengths still exists.

**Comment by gvilarino** [comment]
Yeah, `sticky-session` under `node 0.12.x` was enough.

No idea about question `3` tho

**Comment by spion** [comment]
Experimental support for sticky-sessions is now also available for recluster via https://github.com/spion/sticky-listen

The implementation works very similarly to sticky-session but the sticky balancing logic is separated from the clustering / reloading / worker management logic.

**Comment by gvilarino** [comment]
I think this issue needs some sort of update since, starting in version 4.0, `node` includes `cluster` as a part of its core.

@spion does `sticky-listen` make sense now that [`cluster` is embedded in `node`](https://nodejs.org/api/cluster.html) and also [marked as `stable`](https://nodejs.org/api/cluster.html#cluster_cluster) ?

**Comment by spion** [comment]
@gvilarino yes it does. node's cluster only supports the "round-robin" and "none" scheduling policies, which means it doesn't support sticky sessions out of the box. Furthermore, it doesn't support zero-downtime code reloads out of the box nor it does any sort of worker monitoring and restarting (recluster supports/does both, and as a matter of fact it builds on top of node's native cluster)

I'm still not really happy about the need to have sticky sessions at all. Sessions should not be stored in the workers but in an external services such as redis (or a different process); that way there would be no need for modules such as sticky sessions at all. Besides, both Fedor's sticky-sessions and sticky-listen break down once you add a proxy like nginx into the mix. However Fedor's solution does work in some circumstances, which is why I implemented support for it as a separate module.

**Comment by gvilarino** [comment]
@spion I'm running `sticky-session` behind a set of HAproxy hosts in 4 separate boxes, inside containers, and it doesn't seem to break. Also, my need for stickiness comes from `socket.io`'s requirement of affinity for negotiating websockets.

**Comment by spion** [comment]
@gvilarino It breaks because the IP of the "client" is always the same - its the IP address of the proxy. Since sticky-session hashes that IP, it will always pick the same worker.

**Comment by gvilarino** [comment]
Yeah, I do have that issue when addressing users behind the same proxy/route. But that isn't that big an issue since I do have a HAProxy in front of my webservers, so there *is* some sort of distribution among all my backends, based on an affinity cookie instead of basic IP.

I do agree that being able to chose a different stickiness strategy for the cluster is great progress on this, and until `socket.io` doesn't solve the handshake in another fasion than relying on landing on the same server initially, I think session-stickyness is a necessary evil. Or is there another way around the issue?

**Comment by spion** [comment]
Yes but you don't get distribution within the node-based clusters with the sticky-sessions module. You might as well not use sticky-sessions (or recluster) at all. You should probably rely only on HAProxy to do the load balancing - you'd just spawn more processes using different ports and add them all to HAProxy.

Whether sticky sessions are a necessary evil or not, I don't know. If you look at [caniuse](caniuse.com/#feat=websockets), it seems like it might be viable to go with just pure websockets for some projects (if you don't have to support older browsers). Then you can avoid the transport-level reasons to keep sessions sticky. The rest will depend on the app and other parts of your architecture.

**Comment by Ajaxy** [comment]
> Of course, that means a total re-code of the socket.io rooms layer. I'm afraid all I can say is that the socket.io API wasn't designed to scale across multiple processes.

It's strange statement, since multi-process should be handled by redis adapters and emitters. You can easily emit message to any room on any worker/process if it's connected with an adapter (see code I provided). The only problem is syncing rooms length, probably it's kind of bug or something.

> It breaks because the IP of the "client" is always the same - its the IP address of the proxy. Since sticky-session hashes the IP to pick the worker, it will always pick the same worker.
Why cookies are not used?

**Comment by spion** [comment]
@Ajaxy its not a strange statement. The api to access the rooms is synchronous. Even if you sync the room data, this means that you give up consistency across the processes (at any point of time, one of the nodes may return different info about a room compared to the others)

I mean sure, you can make it work and all, but the original API design was clearly not meant to do that :)

> Why cookies are not used?

Because the balancer will need to read and analyze the data from the socket in that case, then somehow make sure to pass the already read data together with the socket through the IPC channel so that the server on the other side can simulate its "arrival". 

Its probably doable, but `sticky-sessions` doesn't do that (and neither does `sticky-listen` ... for now). It will definitely hurt performance, but I'm not sure how much.

**Comment by Ajaxy** [comment]
Is reading cookie header the real problem on that level? What about some request parameter? `socket.io` is adding `sid` parameter, probably we can rely on it? The request URI looks like
ws://stg.fast.mozggame.ru/socket.io/?EIO=3&transport=websocket&sid=j_qXjBeS4eY_1j5PAAAA

**Comment by spion** [comment]
@Ajaxy I started work on this [here](https://github.com/spion/sticky-listen/blob/use-headers/lib/header-parser.js) and the performance so far looks promising (1 million header extractions per second). 

What should the strategy be though? Cookie, fallback to x-forwarded-for, fallback to ip address? How to gracefully handle no-cookie -> cookie transition?

**Comment by makkesk8** [comment]
A little late probably but, I solved this problem using pm2, redis as the adapter and HAproxy using cookies as the sticky component.

It's been stable so far and it works like a dream. If you haven't already solved it and want more info I'd be happy so supply it.

**Comment by songguangyu** [comment]
just use pm2 cluster socket cliend always reconnect and httpcode 400 502，谁能解决这个问题啊？

**Comment by darrachequesne** [comment]
For future readers, I've added some documentation here: https://socket.io/docs/v4/cluster-adapter/#With-recluster
