### ISSUE TITLE
I can steal packets

### ISSUE THREAD

**Issue by oliverhausler** [socketio/socket.io#2320]
I have tried to grab the url of GET requests and repeat them from a different machine. I haven't investigated into this any further, but it could be a security leak.

What typically happens is that the socket gets disconnected and a new socket is created with a different sid. But despite of that, I sometimes managed to receive data back on the repeated GET from the wrong machine. Whatever that is, but I should receive a 4xx exception, and not 200 with a body.

**Comment by oliverhausler** [comment]
I am cross-referencing https://github.com/socketio/socket.io/issues/2310 because I believe the IP of the original request should be kept together with the sid when a socket is created, and any request from a different IP should not even be answered.

I admit DDOS attacks should be caught at the firewall level, but any product should not answer requests from an IP that is obviously wrong.

**Comment by oliverhausler** [comment]
I have tried to intercept a connection open request from another machine, after the sid had been returned already, and the server gave it to me another time:

 	ÿ0{"sid":"41lAac_PodUHurjaAABw","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}

I guess this needs to be fixed urgently, as it would allow anybody to read packets just by repeating the request.

**Comment by LordMajestros** [comment]
+1

**Comment by LordMajestros** [comment]
What intercept methods have you been using?
Does using SSL mitigate this?

**Comment by oliverhausler** [comment]
I've been using Charles to view the urls as they've been sent, then repeated a url from any system. As GET requests were used, I could paste these into any browser to grab the queued packets that were meant for the original device.

SSL doesn't mitigate the problem because I created a new connection between the browser and the server.

**Comment by vipersec** [comment]
Interesting, a proof of concept would be good.

**Comment by LordMajestros** [comment]
I am not familiar with Charles. Can you view urls sent over SSL using Charles?

**Comment by LordMajestros** [comment]
Trying to reproduce this. 
Did you use Charles' SSL Proxying feature as documented here https://www.charlesproxy.com/documentation/proxying/ssl-proxying/

**Comment by oliverhausler** [comment]
Yes, you use Charles as a proxy, which you specify in Android wifi settings. The url inclusive of all query parameters is never encrypted, even when using SSL. This means you should always see the complete url there as it is called.

Otherwise, you could also log the url to LogCat from your Android app, copy it there and paste it into your PC/Mac browser.

**Comment by tutman96** [comment]
I would like to point out that HTTPS is built on top of TLS. The query string, url, headers, everything in an HTTPS request is encrypted over that TLS pipe. The way Charles proxy works is that it generates a self-signed certificate to match the host name of the server you are trying to connect to. Putting something in the query string of a URL is just as secure as putting it in a POST body (albeit easier to copy and paste).

**Comment by oliverhausler** [comment]
I think that is correct, you could prevent a man-in-the-middle/replay attack by using a cert from an authority, not self-signed, or by checking the signature. @tutman96 I'm not a security expert, please confirm this is correct.

I still believe the product should have basic protection against requests from the wrong endpoint, no matter how it is configured.

**Comment by tutman96** [comment]
Correct. A certificate that has been issued by a trusted certificate authority would allow you to prove the identity of the server. There would be no way of sticking a proxy in the middle to intercept the traffic without trusting the proxy as a certificate authority. There would be no easy way that socket.io could prevent someone from spoofing their endpoint. It would require hash signing and more client library work to even be feasible. And even then, would be impossible to prevent. If someone had access to my computer, for example, they could take some cookies from Facebook and "log in" to facebook as me. There is no way to prevent that.

Just putting this out there, I am not a security expert in any sense. I have just had a lot of experience in the field and am comfortable with the topic.

**Comment by makkesk8** [comment]
@tutman96 +1

**Comment by Locour** [comment]
Are there any updates on this security concern?

**Comment by hichamh** [comment]
Are there any updates on this topic?

**Comment by darrachequesne** [comment]
For future readers:

The session ID (the `sid` query parameter) must not be shared with others, as it *might* allow an attacker to impersonate the real user and receive packets for the session. Using SSL should protect you though.

That being said, even with a valid session ID, an attacker would have to send a request when the real user is in the middle of two long-polling requests, and has not upgraded to WebSocket yet:

- HTTP 500 response in case of a request overlap: https://github.com/socketio/engine.io/blob/7e9e544a9ac4365ef055c9482cc1e9fed624031c/lib/transports/polling.js#L59-L66

- HTTP 400 response in case the WebSocket connection is already established: https://github.com/socketio/engine.io/blob/7e9e544a9ac4365ef055c9482cc1e9fed624031c/lib/server.js#L155-L163

Note: associating the IP address with the session ID means that we'd have to take in account the `x-forwarded-for` headers (or any platform-specific header, like `cf-connecting-ip`)

Note²: passing the session ID in the header has been suggested (https://github.com/socketio/engine.io/pull/577), but we would still need the query parameter for the WebSocket connection, so that does not really solve the problem.

Please reopen if needed.
