### ISSUE TITLE
IIS (iisnode) Sticky Session

### ISSUE THREAD

**Issue by fbacker** [socketio/socket.io#2345]
Trying to use iisnode. I want the app to use all the CPU;s and because of socket.io I need it to be sticky.
When using more than one CPU nodeProcessCountPerApplication it seems that the client getting on a new thread (example on polling - my test GUI).

How do I setup IIS to be sticky? What am I missing?

    <iisnode
          nodeProcessCountPerApplication="0" 
      node_env="stage"
      
      nodeProcessCommandLine="node.exe --nouse-idle-notification --expose-gc --max-old-space-size=8192"
      
      maxConcurrentRequestsPerProcess="10000" 
      watchedFiles="*.js;iisnode.yml" 
      
      maxLogFiles="2"
      />

**Comment by fbacker** [comment]
After some more digging it looks like the issue is somewhere with iisnode giving error back. 
Started this thread with the issue https://github.com/socketio/socket.io/issues/2346

**Comment by VinayParasrampuria** [comment]
Dear fbacker 

Plz let me know if you got this issue solved .I am facing this issue when there are many concurrent request some of them are failing with message "<p>iisnode encountered an error when processing the request.</p><pre style="background-color: eeeeee">HRESULT: 0x6d
HTTP status: 500
HTTP reason: Internal Server Error</pre><p>You are receiving this HTTP 200 response because <a href=https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/web.config>system.webServer/iisnode/@devErrorsEnabled</a> configuration setting is 'true'.</p><p>In addition to the log of stdout and stderr of the node.exe process, consider using <a href=http://tomasz.janczuk.org/2011/11/debug-nodejs-applications-on-windows.html>debugging</a> and <a href=http://tomasz.janczuk.org/2011/09/using-event-tracing-for-windows-to.html>ETW traces</a> to further diagnose the problem.</p><p>The node.exe process has not written any information to stderr or iisnode was unable to capture this information. Frequent reason is that the iisnode module is unable to create a log file to capture stdout and stderr output from node.exe. Please check that the identity of the IIS application pool running the node.js application has read and write access permissions to the directory on the server where the node.js application is located. Alternatively you can disable logging by setting <a href=https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/web.config>system.webServer/iisnode/@loggingEnabled</a> element of web.config to 'false'."
