### ISSUE TITLE
latest Socket IO not compatible with 1.1 code

### ISSUE THREAD

**Issue by dfsdfsdfs** [socketio/socket.io#2378]
Client connects to server. Nothing works but there's no error message.

**Comment by Sammaye** [comment]
Personally apart from the recent array to object change mine works from 0.9 so you could maybe describe more? Give more clues etc

**Comment by dfsdfsdfs** [comment]
Nope. If I could I would've described it already.

**Comment by Sammaye** [comment]
What are you trying to run? Can you show some code?

**Comment by Sammaye** [comment]
And it doesn't error out, as you say the client connects?

**Comment by Levino** [comment]
I have the same issue. I was able to fix it by using version "~1.3.5" (installs 1.3.7). I include socket.io-redis too.

**Comment by darrachequesne** [comment]
Hi! May I ask which version of `socket.io`, `socket.io-client` and `socket.io-redis` do you use?

**Comment by Levino** [comment]
Of course.

These are the dependencies of the server package:

```json
{
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-nodemon": "^2.0.4",
    "mocha": "^2.3.4",
    "mongodb": "^2.0.33",
    "should": "^6.0.3",
    "socket.io-client": "^1.3.5"
  },
  "dependencies": {
    "bitcore-lib": "satoshipay/bitcore-lib",
    "bitcore-message": "^1.0.2",
    "freeport": "^1.0.5",
    "http-post": "^0.1.1",
    "kue": "^0.9.4",
    "random-js": "^1.0.4",
    "redis": "^0.12.1",
    "request": "^2.55.0",
    "satoshipay-nano-logger": "^0.5",
    "satoshipay-nano-models": "^0.9.14",
    "socket.io": "^1.3.5",
    "socket.io-redis": "^0.1.4"
  }
}
```

These are the dependencies of the client

```json
{
"dependencies": {
    "async": "^0.9.0",
    "bitcore-lib": "satoshipay/bitcore-lib",
    "bowser": "^1.0.0",
    "browser-request": "^0.3.3",
    "browsernizr": "^2.0.0",
    "cookie": "^0.2.2",
    "gulp-compile-handlebars": "^0.5.0",
    "jquery": "^2.1.4",
    "jquery.isinview": "^1.0.1",
    "lodash": "^3.10.0",
    "path-browserify": "0.0.0",
    "rangeslider.js": "^1.2.2",
    "satoshipay-nano-client": "^0.7.5",
    "satoshipay-nano-logger": "0.5",
    "shortid": "^2.2.2"
  },
"devDependencies": {
    "browser-sync": "^2.9.8",
    "browserify": "^9.0.8",
    "browserify-shim": "^3.8.5",
    "del": "^1.2.0",
    "envify": "^3.4.0",
    "finalhandler": "^0.4.0",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^2.1.0",
    "gulp-jshint": "^1.10.0",
    "gulp-less": "^3.0.3",
    "gulp-minify-css": "^1.2.1",
    "gulp-mocha": "^2.0.1",
    "gulp-nodemon": "^2.0.2",
    "gulp-rename": "^1.2.2",
    "gulp-replace": "^0.5.3",
    "gulp-streamify": "0.0.5",
    "gulp-uglify": "^1.2.0",
    "gulp-util": "^3.0.4",
    "handlebars": "^3.0.3",
    "hbsfy": "^2.2.1",
    "mongodb": "^2.0.45",
    "satoshipay-nano-backend": "^0.3.17",
    "satoshipay-nano-demopage": "^0.1.5",
    "serve-static": "^1.9.3",
    "uglifyify": "^3.0.1",
    "vinyl-source-stream": "^1.1.0",
    "watchify": "^3.1.2"
  }
}
```

Interestingly if I run the server "standalone" it works, because ```npm install``` for the server package does install socket.io@1.3.5.

But for development for the client software the server service is being started by gulp via the satoshipay-nano-backend service. ```npm install``` in the client package (same version of the websocket service package through backend package) will install socket.io@1.4.3 and then it fails. (Took me quite some time to figure this sh*t out :D)

**Comment by Levino** [comment]
It also breaks when I use socket.io@1.3.7 and socket.io-redis@1.0.0 (socket.io-redis@0.1.4 is using redis-adapter@0.3.1, socket-io.redis@1.0.0 is using redis-adapter@0.4.0) Maybe the redis adapter is where the issue lies?

**Comment by thedewpoint** [comment]
+1 I had this issue as well, wish I checked here first because it took me all day to figure out what caused it.  Same exact solution as well, had to go back to 1.3.7, not sure if we should be posting this on the adapter.

**Comment by huineng** [comment]
The problem is that the socket now have a forward slash hash like /#QRCxkPJivlgEQDzSAAAN so i also had to go one version back

**Comment by darrachequesne** [comment]
The socket.id has indeed slightly changed in 1.4.x version ([here](https://github.com/socketio/socket.io/blob/master/lib/socket.js#L62)), in order to be used as a unique index value in `Socket` map:
`this.id = nsp.name + '#' + client.id;` instead of simply `this.id = client.id;`

But it does not seem related there, according to @Levino comment.

**Comment by darrachequesne** [comment]
Well, I think `̀socket.io-redis@1.0.0` is not compatible with `socket.io-adapter@0.3.1` (that socket.io@1.3.7 depends on), due to the new Room object.

Dependency matrix:
`socket.io-redis@1.0.0`: `socket.io@1.4.x` > `socket.io-adapter@0.4.0`
`socket.io-redis@0.1.4`: `socket.io@1.3.7` > `socket.io-adapter@0.3.1`

**Comment by Levino** [comment]
Can anyone confirm that ```socket.io-redis@1.0.0``` works when latest ```socket.io``` (1.4.4) is installed? Will test later.

**Comment by whattokingu** [comment]
Using [this repo](https://github.com/whattokingu/socket.io-redis-sample) and the corresponding versions of socket.io and socket.io-redis, it appears to be working.

**Comment by awdogsgo2heaven** [comment]
@Levino it appears 1.4.4 and redis 1.0.0 is working.
