### ISSUE TITLE
tutorial has you place a script BEFORE body and doesn't work

### ISSUE THREAD

**Issue by ksullivan2** [socketio/socket.io#2467]
In the chat tutorial, the instructions specifically state:

> Now in index.html I add the following snippet **before** the body:
> 
> ``` .html
> <script src="/socket.io/socket.io.js"></script>
> <script>
>   var socket = io();
> </script>
> ```

However, the next time this code is edited, it will need to reference elements that are created within the body.

``` .html
<body>
    <ul id="messages"></ul>
    <form action="">
      <input id="m" autocomplete="off" /><button>Send</button>
    </form>
  </body>

  <script>
    var socket = io();
    $('form').submit(function(){
      <!--these lines reference element 'm', which is created in the body-->
      socket.emit('chat message', $('#m').val());
      $('#m').val('');
      return false;
    });
  </script>
```

Simply changing the word BEFORE to AFTER in the first instruction would fix the issue. New users, especially those new to programming/JS/HTML in general, may not catch the error and become frustrated by a tutorial that seems not to work (there are multiple Stack Overflow posts about this, such as [this one](http://stackoverflow.com/questions/27711699/not-getting-the-values-passed-by-the-socket-io-client)).

**Comment by baconface** [comment]
The tutorial is correct as I can see. Note it says before the ```</body>```. Not before the body. It is referring to the closing body tag and not the body itself.

**Comment by ksullivan2** [comment]
Oh! I completely missed that "/''. Perhaps it could be clarified to say
"before the closing </body> tag" to avoid that confusion in the future.
Thanks for responding!

**Comment by jameskraus** [comment]
This is not intuitive. It is very easy to misread this statement and place the scripts in the head, before the "<body>", where they are usually found. jQuery does not allow for selection of elements off the bat, so pasting the code in the head will cause the $("form") selector to fail. It would be easy to mitigate this two ways:

Change the code to include a $().ready(function{....}); wrapper, so that it works if it is placed in the head.
Change the wording to say "after the "</form>", which makes it obvious that the code needs to be placed in the body (out of the norm), and after the form element.

Example of someone misreading this over a year ago:
https://github.com/rauchg/chat-example/issues/9

If you search around Stackoverflow, there are some other users which have the same problem without realizing it.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
