### ISSUE TITLE
Compression and caching

### ISSUE THREAD

**Issue by THE-Swank** [socketio/socket.io#2473]
how to enable compression and caching for /sockets.io/sockets.io.js?

**Comment by THE-Swank** [comment]
and why not minimize /socket.io/socket.io.js
/socket.io/socket.io.min.js?

**Comment by baconface** [comment]
What do you mean by caching? Sockets are used for live data. It is best to implement your own client side if you wish to retain something. Otherwise you shouldn't be pushing data the client doesn't need or already has as that is a waste of resources.

I think the reason for no minimized file is because that part is server side unlike its socket.io-client counterpart. You wouldn't gain much if anything from removing the whitespace.

**Comment by THE-Swank** [comment]
Is it possible to enable gzip compression for http://mobicms.the-swank.pp.ua:3000/socket.io/socket.io.js ?

**Comment by jahak7** [comment]
@THE-Swank https://cdnjs.com/libraries/socket.io

**Comment by jahak7** [comment]
@THE-Swank https://cdnjs.com/libraries/socket.io

**Comment by baconface** [comment]
Ah, gotcha. You mean the client side file and not the transport. Then yes, you could use the [CDN](https://cdnjs.com/libraries/socket.io).

As far as transports. Not many browsers support compres for WebSockets. So if it was implemented you are looking at restricting your target browser to certain modern browsers. Likely not worth it for most socket.io users. You can find a [demo here](https://github.com/socketio/socket.io-compression-demo) though.

**Comment by THE-Swank** [comment]
without a CDN?

**Comment by baconface** [comment]
You can do it yourself as well as minify the rest of your project with [build tools](https://github.com/mishoo/UglifyJS2).
