### ISSUE TITLE
Socket.IO is creating too many subdirectories for Windows

### ISSUE THREAD

**Issue by Coder206** [socketio/socket.io#2540]
I am running a Windows 10 64 Bit computer and I am working with Socket.IO v1.4.5. Whenever I run NPM install, the engine installs it's dependencies. When I come to delete these to modify my code, it says it's impossible as there are too many directories and Windows doesn't allow me to do anything. I have also tested on Fedora 23, the issue was not reoccurring. Anyone working on a fix for this? Thanks for your time!

**Comment by ilbonte** [comment]
Which version of npm are you using?

**Comment by Coder206** [comment]
I am running NPM 2.14.20

**Comment by ilbonte** [comment]
This issue is been fixed since npm@3 
Quoting from [changelog](https://github.com/npm/npm/releases/tag/v3.0.0)

> Your dependencies will now be installed maximally flat. Insofar as is possible, all of your dependencies, and their dependencies, and THEIR dependencies will be installed in your project's node_modules folder with no nesting. You'll only see modules nested underneath one another when two (or more) modules have conflicting dependencies.

If you have git bash installed you should be able to remove node_modules running `rm -rf /c/users/mynodeproject/node_modules`

if not you can try https://www.npmjs.com/package/rimraf 

`npm install rimraf -g`

And in the project folder delete the node_modules folder with:

`rimraf node_modules`

**Comment by Coder206** [comment]
Thanks for your help @ilbonte! I actually am used to auto updates and such fancy code. I wasn't aware I an old NodeJS build. Now enjoying 3.8.6 (npm)!
