### ISSUE TITLE
Node.js app error when loading Socket.Io

### ISSUE THREAD

**Issue by jbeckton** [socketio/socket.io#2554]
I am running Node.js (Centos 7) and I just started to implement Socket.io.

The only line of code I have regarding Socket.io is in my /bin/www file

`var io = require('socket.io')(server);`

The app blows up with an error:

> error Cannot find module 'bufferutil'

I have done 

> npm install bufferutil --save

 but does not fix the issue.

**Comment by jbeckton** [comment]
`npm install bufferutil --save
> bufferutil@1.2.1 install /home/jbeckton/Documents/Projects/SPOG/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/home/jbeckton/Documents/Projects/SPOG/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
./Release/.deps/Release/obj.target/bufferutil/src/bufferutil.o.d.raw { dev: 64769,
  mode: 33188,
  nlink: 1,
  uid: 862519,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 151760278,
  size: 1358,
  blocks: 8,
  atime: 2016-05-19T19:41:44.000Z,
  mtime: 2016-05-19T19:41:44.000Z,
  ctime: 2016-05-19T19:41:44.884Z,
  birthtime: 2016-05-19T19:41:44.884Z }
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory `/home/jbeckton/Documents/Projects/SPOG/node_modules/bufferutil/build'
`

**Comment by jbeckton** [comment]
Same issue with utf-8-validate

**Comment by jbeckton** [comment]
FYI: Was just over at the bufferutil github page searching for answers and the admin stated that there is no one around to support that code anymore.

**Comment by MasterJames** [comment]
Maybe try a different OS?

**Comment by MasterJames** [comment]
Trying a Stranger comment.
Version of python?  3 or 2.7?

**Comment by MasterJames** [comment]
Try delete your node_modules and do a fresh npm install but not nodes 6

**Comment by jbeckton** [comment]
I wish I could use a different OS but I have to use what the company provides. I rebooted and it started working, probably a perms issue or a locked file?

I have python 2.5

is there a known issue with Node 6 and this module? If so I will downgrade cause I need this to work when it's deployed via Continuous Integration, our environment is all automated so i need to mitigate any issues before I push this into our pipeline for deployment.

Thanks

**Comment by MasterJames** [comment]
I don't know was think about meteor in regards to nodejs v6.
Python 2.7 sounds better to me.

**Comment by gaboom** [comment]
+1 Something is wrong with Socket.io in current release. You can install it no problem, but it won't work at all. Basically if you follow your own guide it will fail http://socket.io/get-started/chat/ complaining about exception from require...

Dependencies bufferutil and utf-8-validate are required but not declared as dependencies. Why? 
So any attempt using Socket.io will fail because it tries to load a dependency nowhere declared.

On the other hand these dependencies appear a piece of junk. Requires Python, Visual C++ SDK, WTF dude, I am not going to install these for JavaScript for the sake of the Lords.

1. Socket.io needs to declare needed dependencies (bufferutil and utf-8-validate)
2. Socket.io needs to declare requirements (Python? VSCPP?)

**Comment by darrachequesne** [comment]
`bufferutil` and `utf-8-validate` are optional dependencies of [ws](https://github.com/websockets/ws/blob/master/package.json#L28), used [here](https://github.com/websockets/ws/blob/master/lib/BufferUtil.js#L10) and [here](https://github.com/websockets/ws/blob/master/lib/Validation.js#L10). If those dependencies are not installed, the fallbacks should be used (yet it doesn't seem to be the case here)

> On the other hand these dependencies appear a piece of junk. Requires Python, Visual C++ SDK, WTF dude, I am not going to install these for JavaScript for the sake of the Lords.

The dependencies are built from native code (see https://github.com/websockets/bufferutil and https://github.com/websockets/utf-8-validate), I think that's why `node-gyp` is needed (bringing Python and such).

@jbeckton what version of node.js / socket.io are you using please?

**Comment by FloMaetschke** [comment]
I have got the same problem

**Comment by XOP** [comment]
+1

**Comment by darrachequesne** [comment]
@FloMaetschke @XOP could you please describe your problem?

**Comment by XOP** [comment]
@darrachequesne   
I have messages about missing `bufferutil` and `utf-8-validate`,  
sorry I can't provide more info, since I (sadly) switched to custom WS implementation,  
but I failed to  find any related and up-to-date issues... there are multiple similar issues related to React, webpack, browserify, livereload etc. I'm using browserify to bundle things on the client, maybe it's an issue.

**Comment by darrachequesne** [comment]
For future readers: please see the documentation [here](https://socket.io/docs/v3/server-installation/#Additional-packages).

**Comment by anztrax** [comment]
thanks @darrachequesne it really helpful 🙏
