### ISSUE TITLE
Can not reuse an existing Manager for subsequent calls in v1.4.8

### ISSUE THREAD

**Issue by fantasy8-me** [socketio/socket.io#2602]
Execute follow code in client, got different result between v1.3.7 and v1.4.8

```
    const API_SERVER='http://mydomain';
    const socket1 = io(API_SERVER);
    const socket2 = io(API_SERVER);
    console.log('socket1 === socket2', socket1 === socket2);
```

v1.4.8

```
socket1 === socket2 false
```

v1.3.7

```
socket1 === socket2 true
```

According to 'http://socket.io/docs/client-api/#client-api', looks like v1.3.7 behave correctly, is it a bug in v1.4.8(or older version) or the api changed?

**Comment by theoutlander** [comment]
I've been noticing this issue as well and it didn't add up to the doc. Looking at the code, it appears that there's a change that was introduced a while back (Jan 2015) in the socket.io-client and that's what seems to not multiplex anymore.

This is the commit where the issue was introduced:
https://github.com/socketio/socket.io-client/commit/7d237cc91fbb34ce484b188cf7d10462c6b34bd9

This is the line that is the problem: 
https://github.com/socketio/socket.io-client/blob/master/lib/index.js#L48

Is this expected? I think it should be changed to NOT sameNamespace:

  var sameNamespace = cache[id] && path in cache[id].nsps;
  var newConnection = opts.forceNew || opts['force new connection'] ||
                      false === opts.multiplex || !sameNamespace;

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
