### ISSUE TITLE
socketio website bug? 

### ISSUE THREAD

**Issue by neo1218** [socketio/socket.io#2641]
![2016-08-12 3 25 36](https://cloud.githubusercontent.com/assets/10671733/17601865/be3c3aaa-603c-11e6-8dd2-71d05c4b0193.png)

> XMLHttpRequest cannot load http://slack.socket.io/socket.io/?EIO=3&transport=polling&t=LPx4Yau. >No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin >'http://socket.io' is therefore not allowed access. The response had HTTP status code 502.

**Comment by MaffooBristol** [comment]
The slack.socket.io page is broken and that's why it's not connecting properly. It also seems that the server running the examples is down. Quite a lot of people in the issues over the past week have been mentioning it, so hopefully @rauchg can bring them back online, otherwise there's nothing else really to add! Thanks

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
