### ISSUE TITLE
NONE OF THE DEMOS ARE WORKING!!!!!

### ISSUE THREAD

**Issue by sungju881203** [socketio/socket.io#2651]
none of the socket.io demos are working.
better fix it.

**Comment by shintabmt** [comment]
The demo server is down.

**Comment by jdc20181** [comment]
It's not only the server is down they don't work on my own server either. I
have a similar issue already created I'll get on after while and reference
it. I made it about 2-3 days ago. Regardless- someone said there's some
sort of syntax error. So even if the server was up- the demos wouldn't
work.
This project is failing- idk who's in charge or the developers but I think
the end is sadly near.

**Comment by MaffooBristol** [comment]
They're working fine for me on my local machine; just pulled a fresh copy.

If you open an issue, could you please give some more details about the environment you're working in rather than writing something like "better fix it", which isn't very helpful.

How did you install the demos and on what environment? Did you follow the instructions at https://github.com/socketio/socket.io/tree/master/examples/chat?

**Comment by jdc20181** [comment]
Sorry but I used the code on another server and it didn't work. Used it
EXACTLY as the code is.
We even tried it on a different work space. When demos don't work on the
live demo part of a project it makes me wanna turn and run because
evidently the project is garbage.

Fixing them is something you do to make it professional and like a freshly
picked bouque of flowers not the dead ones you threw out last week.

I do not have the time to try and "fix" stuff that isn't working - copying
local WILL NOT FIX IT.

If I wanted it local I would have ran it local. I need the chat part for a
chat system of a project we wanted to take no more than a few months on.

I don't think I will ever Reccomend this project to anyone again if stuff
isn't gonna work properly. It's unprofessional and not worth my time.

**Comment by MaffooBristol** [comment]
Well that was a delightful rant, very impassioned. ⭐ ⭐ ⭐ ⭐ ⭐ 

Are you going to actually provide anything constructive then, or are you just going to say a project is garbage because you can't get an example it provides to work? Yes, the live examples are down, no idea why, but nothing I can do about it. However, if you can't get the project to work after pulling the code and installing the dependencies as instructed, and you don't then provide the operating system, steps to reproduce, even the errors you're getting, but just go on a tirade, what exactly to you expect from people who may be able to help?

The fact that I pulled the code and got the example running within a couple of minutes shows that it's not broken. And I get you don't want it running locally, but that makes no difference. It should deploy just fine on different OSes; stating I got it working on my local Mac rather than a remote Linux box is inconsequential.

**Comment by jdc20181** [comment]
I followed the instructions to build the demos- and even the other person
working on this project copied code line for line.
It still DOES NOT WORK.
It's on cloud 9 is where we work on it at.

**Comment by MaffooBristol** [comment]
Okay cool, well that's a start. When you run it, do you see the `Server listening at port 3000` message at the end? If so, that means it's built and is running fine. But that doesn't mean you necessarily have access to port 3000, because I reckon c9.io is only going to open port 80 by default, so you may need to change it to run on port 80, open the iptables to allow port 3000 or port forward it via nginx or something like that.

If that's not the case, and it's coming up with some sort of error when running `node .`, could you please copy and paste it? Or if the errors are coming up during `npm install` then c&p those.

Thanks.

**Comment by jdc20181** [comment]
how do you do this "change it to port 80" and how will it affect our chat system after we port it to our server? 

I need to know otherwise we are going to spend 2X longer hiring a php developer to develop one from scratch. 

I will get back on the "exact" error but it was a syntax error of some sort I am not into backend stuff so its lke a blind person walking into a trap. I don't fool with this kind of stuff. 

I can do some js but not this stuf lol

**Comment by MaffooBristol** [comment]
Either add the port environment variable before you call the script, eg `PORT=80 node .` - or change the value to 80 on line 6 of index.js. But normally I'd recommend getting nginx to forward it.

To be honest, I think you're going down the wrong route trying to just plug and play the example from socket.io to use as a chat room, especially if you're not very well versed on how node works. It's not designed to be a chat room client, it's just, as it says, an example that's meant to show you the basics of the API. There are loads of chat room clients out there- this is a custom API for building your own realtime apps, not something designed to be dropped in and work instantly without any knowledge of server config.

If there is a syntax error that's actually a problem with socket.io then I'm happy to hear it and try and sort out the problem, but it sounds to me like it may just be a configuration issue...

**Comment by jdc20181** [comment]
I'll have to get back with you with the exact one we have since given up.
We have someone who knows node enough to fix it we just wanted to see how
it worked- we wanted to see if we could do what was intended. We are
building a social network of sorts- and it's going to be sort of like
messenger and connected- and so forth.
But the difference is we are gonna have hundreds of chat rooms on various
topics.

Maybe I should ask this- what is the advancements we can do with socket?
Can we connect it to our database with PHP ? What are the disadvantages or
limits? What is the best way to get it visually looking good? Are there
ways to get what we are wanting easy? Thanks

**Comment by MaffooBristol** [comment]
Socket.io is exclusively node. You could connect it to MySQL or whatever, but not via PHP. Though if you're doing live stuff, something like Couchbase or Mongo would be better suited for persisting data.

But anyway, this isn't really the best place for that type of discussion. Maybe try stack overflow?

**Comment by jdc20181** [comment]
Isn't the best place to discuss it? That really makes me wanna use it close
the issues I made I am not gonna be replying.

We will find a better solution.

**Comment by MaffooBristol** [comment]
Maybe you need a little reality check. No-one cares whether or not you use this project.

You're not doing anyone a favour by choosing to use it. In fact, bearing in mind that this is free and open sourced code that you get to use as you wish, it's pretty rude to just completely slag off the project and be entirely ungrateful to people who are taking the time to help you.

And yes, this isn't the best place to discuss it. It's Github issues, not a question and answer site; and although 99% of the time people will just help someone out within Github issues anyway, it's not what it's designed for, especially when the discussion is going off-topic completely from the original issue and you're trying to help out someone who's acting like a petulant child. And you may not have noticed, but there are a lot of open issues!

Also, a lot of things you're asking are nothing to do with Socket.io at all. How to make it look good? I don't know, hire a designer?

Feel free to find a better solution. Good luck with your social media site.

Matt.

**Comment by hairyhenderson** [comment]
The demo server seems to be back up now... Maybe this issue should be closed?

**Comment by jdc20181** [comment]
Ok first of all- idc. Open source or not I asked a simple question.
I am not going to use that site I hate it.
Third- I know what github is. I have many of my own projects and know you
don't care if I come or go. That's fine.
Thanks for letting us know it's back Dave.
Close this issue if you must.

**Comment by rauchg** [comment]
Fixed! Won't happen again
