### ISSUE TITLE
Disconnect after failed authorization handshake

### ISSUE THREAD

**Issue by Vanuan** [socketio/socket.io#2699]
If I understand the protocol correctly, websockets doesn't have any authentication mechanism.
So there's this socket.io internal protocol which ignores all messages after the first error passed to next in middleware.
Am I right?

Is it possible to have some configuration option so that according to this socket.io protocol, it not only ignores messages, but actively disconnect the client?

Alternatively, is the a way to disconnect the client right after he receives an error message?

I don't think it makes any sense to keep the connection alive if there's some error in socket.io handshake protocol.

**Comment by carpii** [comment]
So I guess you have registered a middleware function to carry out your auth?

Once you detect auth has failed, have you tried just calling socket.disconnect()?
It already has a handle to the client socket

**Comment by Vanuan** [comment]
> Once you detect auth has failed, have you tried just calling socket.disconnect()?

How do I send the client the reason of the disconnect?

**Comment by carpii** [comment]
You can just call socket.emit("kicked", {msg: "Bye Bye!"}) prior to calling socket.disconnect()

As far as I know it will still be received by the client (at least this is what I use, and I have yet to see a time where it wasnt)

**Comment by Vanuan** [comment]
I verified and no, it doesn't reach the client.

**Comment by carpii** [comment]
Hrm, ok. Perhaps its a race condition, I can still reproduce it here but it may well be dependant on latency somehow

In that case I guess you've a couple of choices..

1) Handle it client side so that if they are disconnected during auth, then you assume auth failed
2) Send the disconnect reason to the client, and flag the socket server-side as disconnecting. Any further incoming messages from this socket should be immediately discarded, and then your server can force-disconnect any sockets in this state at regular intervals.

I assign my own status codes to each socket server-side to help track this (ie CONNECTING, CONNECTED, JOINED, DISCONNECTING, DISCONNECTED)

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
