### ISSUE TITLE
`Server#attach(srv:http#Server, opts:Object):Server` whah?

### ISSUE THREAD

**Issue by MichaelJCole** [socketio/socket.io#2719]
Hey, this is a cool project, but the documentation is practically useless to me because I don't know what these function signatures mean:

```
Server#attach(srv:http#Server, opts:Object):Server
```

I think it's you extra work in the issue queue, and on stackoverflow.

**Comment by carpii** [comment]
I agree, the socket.io docs are next to useless. It's better to state the problem you are having and ask for a solution

I offered to help try to improve the docs some time ago, but there are some trust issues I think :-)

**Comment by richb-hanover** [comment]
@carpii  writes:
> I agree, the socket.io docs are next to useless. It's better to state the problem you are having and ask for a solution

@carpii I will second this comment. I've submitted two notes (#2717, #2723) without any response - Am I stating the problem well? Can you suggest anything else I could do to help the maintainers? Many thanks.

**Comment by carpii** [comment]
@richb-hanover  I think you explained the problem better than most Issues on this github. I'll to help although I;m really no expert, just trying to help out as I don;t want socket.io to gradually fade into obscurity due to a massive Issue list.

I think it would be worth closing your 2nd #2723 ticket though, as its pretty much a duplicate.

I've replied on #2717
