### ISSUE TITLE
Critical buffer.js / "Maximum call stack" exception - Brings down the server

### ISSUE THREAD

**Issue by kaansoral** [socketio/socket.io#2727]
```
buffer.js:319
    if (!isFinite(length)) {
         ^
RangeError: Maximum call stack size exceeded
```

This was on stderr when the server crashed, I don't have any steps to reproduce or have any idea why this happened

Edit: Server's NPM version seems to be 1.4.8, while the latest is 1.5.0

**Comment by carpii** [comment]
@kaansoral stack overflow is nearly always caused by recursion (even if its unintentional).

Add some logging to ensure your server-side event handlers are not triggering other methods (which then in turn trigger the caller).

Its also possible your node environment is simply running out of stack space, but that would be unusual unless you are passing huge parameters to other functions by value

**Comment by darrachequesne** [comment]
Related: https://github.com/websockets/ws/issues/758

**Comment by darrachequesne** [comment]
That should be fixed now, thanks.
