### ISSUE TITLE
one server machine only support 65536 clients to connect by socket?

### ISSUE THREAD

**Issue by chelsh** [socketio/socket.io#2994]
one server machine only support 65536 clients to connect by socket?  we have 600000 users, need a lot of server machine?

**Comment by LordMajestros** [comment]
No. One machine has 65536 ports for connection. One port can handle all your connections you just need enough ram.On 4 Jul 2017 3:18 am, chelsh <notifications@github.com> wrote:one server machine only support 65536 clients to connect by socket?  we have 600000 users, need a lot of server machine?

**Comment by kapouer** [comment]
Given a fixed remote ip and a fixed server ip, this remote can open a maximum of 65536 simultaneous tcp connections to this server through this ip, because it cannot open more than this much "ephemeral ports".
But two different remote ip can get the same ephemeral port, so you're just fine.
Unless each client is going to ask the server to open a connection to another server for him (but that would be bad design).
Actually, using uws module, the first thing you're going to run out of is CPU. Then RAM, then bandwidth if you're not transfering that much data.

**Comment by kapouer** [comment]
Also you're going to need to fiddle with some kernel options. I recommend
```
net.ipv4.ip_local_port_range = 8000 65500
net.nf_conntrack_max = 2097152
net.core.somaxconn = 32768
net.netfilter.nf_conntrack_max = 2097152
net.netfilter.nf_conntrack_tcp_timeout_established = 500
fs.file-max = 3289768
fs.nr_open = 1048576
```

Also you need to keep a high NOFILE limit (like 200000). If your service is driven by systemd, this can be tricky to achieve.

**Comment by Arcanorum** [comment]
This sounds like like a JavaScript problem with the maximum number of properties on a single object being exceeded.
