### ISSUE TITLE
How does socket.io handle unexpected websocket closes and timeouts

### ISSUE THREAD

**Issue by mtennoe** [socketio/socket.io#3056]
Hi all

This is more of a question than an issue.

In a project I am working on, we are using WebSockets to connect to our service from the browser clients. This works relatively well, but we are seeing some issues: We are seeing that websockets close unexpectedly, which can happen for many reasons (network issues, background tabs, etc). This we cannot prevent, so we need to have proper error handling in these cases. 

The main issue here seems to be that the various browsers are reacting inconsistently to these websocket issues, where some browsers close the WS very shortly after the issue appears, while others have a longer timeout (20-30 seconds for instance), where you can still write to the websocket (the message never reaches the server ofc). We need the WS to fail quicker than that in our application though, as it has some fairly strict performance requirements, and we want to act on the failure quickly.

Looking at various frameworks and projects using websockets, it seems to be common for the server to send pings to the client regularly (on the application level), where the client then considers the WS as dead if it doesn't receive X amount of pings in a row. I know for instance SignalR does this.

How does socket.io handle this?

Thanks!

**Comment by psabharwal123** [comment]
if you read server api docs, at the very top -

Among those options:

pingTimeout (Number): how many ms without a pong packet to consider the connection closed (60000)
pingInterval (Number): how many ms before sending a new ping packet (25000).

Those two parameters will impact the delay before a client knows the server is not available anymore. For example, if the underlying TCP connection is not closed properly due to a network issue, a client may have to wait up to pingTimeout + pingInterval ms before getting a disconnect event.

**Comment by mtennoe** [comment]
Aha, I should have looked better at the docs first, my bad.
Thank you!
