### ISSUE TITLE
Socket disconnecting multiple times

### ISSUE THREAD

**Issue by soravmobi** [socketio/socket.io#3116]
Hello,

My socket disconnect event calling multiple times, I am using pingInterval & pingTimeout params and sometimes its working fine, sometimes getting disconnect continuously.

var server             = require('https').createServer(options,app),
	  io                 = require('socket.io')(server,{
	  						 pingInterval: 10000, // In MS (1S = 1000 MS)
  							 pingTimeout : 5000
	  						}),
Please let me know as soon as.

**Comment by Reckfu1** [comment]
my socket also disconnect event multiple times... it's strange

**Comment by jonathan-casarrubias** [comment]
Anyone found any solution? I have found this issue while updating to a 2.x version of socket.io.

I have been using 1.7 for a while now which does not present this issue, but now I need to update because I'm having issues with older versions of socket.io-adapter so I have this problem that if I upgrade to 2.x it keeps disconnecting, but if I downgrade to 1.7 I have problems with older adapters.

Please share if you found any solution

I have tried

```json
{
  transports: ['websocket'], upgrade: false
}
```

and 

```json
{
        log: false,
        secure: LoopBackConfig.isSecureWebSocketsSet(),
        forceNew: true,
        forceWebsockets: true,
        transports: ['websocket']
}
```

The former configuration is the one I have been using a while on 1.X

**Comment by darrachequesne** [comment]
For future readers: please check https://socket.io/docs/v3/troubleshooting-connection-issues/
