### ISSUE TITLE
IIS10 SSL RANDOM ECONNRESET

### ISSUE THREAD

**Issue by globules-io** [socketio/socket.io#3228]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS: Windows Server 2016
- browser: Any
- socket.io version: 2.0.4

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

Just randomly pops up "ECONNRESET" error with IIS. SSL cert is a regular SSL (not self signed). Socket.io only throwing this error random .

**Comment by globules-io** [comment]
Let me add a bit more info.
Server is a Windows Server 2016 + IIS 10 running on port 80 & 443, websockets NOT enabled
Node + Socket.io are running SSL on port 8081
In short, they are not talking to each other, not running on the same ports.

**Comment by kjr247** [comment]
If you can produce your documentation on how you set this up I will gladly follow every step and find the fix for you. 

btw I totally forgot you have to turn off iis websockets feature when using iisnode/socketio. Thanks for that info!

I'll say off the top of my head is your node server behind a load balancer? Are you using multiple cores? Both of these things can cause re-connections, and reconnecting can cause this error occasionally.

**Comment by globules-io** [comment]
I am not using iisnode. I'm not handling that port through IIS. Node/Socket.IO is untouched by IIS.
Not behind a load balancer. Multi core CPU but Node is single threaded anyway..

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
