### ISSUE TITLE
When client receives reconnect event socket.connected is false

### ISSUE THREAD

**Issue by qiulang** [socketio/socket.io#3269]
* [x] report a *bug*

As the document https://socket.io/docs/client-api/#event-reconnect said "Fired upon a successful reconnection." when I check socket.connected then, it is still false.

### Current behaviour

socket.connected is false on reconnect event

### Expected behaviour

socket.connected is true on reconnect event as the document said it is fired upon a successful reconnection 

### Setup
- OS macOS 10.13:
- browser chrome 66/67:
- socket.io version 2.1:

**Comment by darrachequesne** [comment]
For future readers: this quite surprising behavior was fixed in Socket.IO v3.

The "reconnect" event actually means that the Manager (which manages the low-level connection) has reconnected, but the Socket instance may not be reconnected yet.

Documentation:
- https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#The-Socket-instance-will-no-longer-forward-the-events-emitted-by-its-Manager
- https://socket.io/docs/v3/client-socket-instance/#Events
