### ISSUE TITLE
Date are stringifyed

### ISSUE THREAD

**Issue by atiertant** [socketio/socket.io#3405]
* [x] report a *bug*
* [ ] request a *feature*

sending a Date object is stringifyed

### Steps to reproduce

```
var server = require('socket.io').listen(4000);
var client = require('socket.io-client').connect('http://localhost:4000');

server.on('connection', function(socket) {
  socket.on('message', function(msg) {
    console.log(typeof msg.myDate); //string
  });
});

client.on('connect', function() {
  client.emit('message', { myDate: new Date() });
});
```

### Expected behaviour

shoud receive a Date Object

### Setup
- OS: Fedora
- browser: Node.js
- socket.io version: 2.2.0

**Comment by deskoh** [comment]
The JSON is probably serialized using `JSON.stringify` and JSON does not support date object (see https://www.w3schools.com/js/js_json_datatypes.asp) so it is converted to string object.

**Comment by atiertant** [comment]
@deskoh yes but what about Buffer... couldn't we have the same behavior ?

**Comment by deskoh** [comment]
What do you mean. Any more specific or concrete example?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by atiertant** [comment]
have a look at https://github.com/socketio/engine.io/blob/e5b307c16d8e7594fcec4eb23508f23f78546dc6/lib/parser-v3/index.js#L75
buffer are encoded in a different way, so can't we do the same with date ?

**Comment by atiertant** [comment]
@darrachequesne could you reopen it ?

**Comment by darrachequesne** [comment]
@atiertant for such a specific use case, I think you should create your own parser. Please see the documentation here: https://socket.io/docs/v3/custom-parser/

**Comment by atiertant** [comment]
@darrachequesne so date object are not supported in socket.io ?

**Comment by darrachequesne** [comment]
> so date object are not supported in socket.io ?

What I meant is that date objects are transferred over the wire as strings, since Socket.IO relies on `JSON.stringify() / JSON.parse()` methods by default.

If you need that those strings should be parsed as plain date objects on the other side (which is a perfectly valid use case!), the best way would be to use your own parser, by using the `reviver` argument of the [`JSON.parse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) method for example:

```js
JSON.parse(payload, (key, value) =>
  if (key === "date") {
    return new Date(value);
  }
  return value;
);
```

Another option is to use the [msgpack parser](https://socket.io/docs/v3/custom-parser/#The-msgpack-parser), which preserve date objects.

**Comment by kputh** [comment]
I think the documentation should state that data is de-/serialized using `JSON.stringify` and `JSON.parse`. These two functions have some suprising behaviour: they do not only replace Dates with strings, but also strip `undefined`-valued properties from objects and replace `undefined` with null in arrays. It may not seem like a big deal, but it implied that types for sending and receiving the same data may not line up at runtime and in TypeScript.
