### ISSUE TITLE
how can make sure fast reconnect while client user at a unstable network environment

### ISSUE THREAD

**Issue by knightchim** [socketio/socket.io#3417]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

*What is actually happening?*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*

### Setup
- OS:
- browser:
- socket.io version:

**Comment by knightchim** [comment]
hello,bros,I m facing a situation while I try to make a group chat job. if mt bowser clients have a poor network,then it always disconnct with ws.I think its ok,it will connect back,BUt,it takes a lot time to really connect again and get stability.

any idears to help to make it reconnect at the most fast way,like what I should do sth in socket.on('disconnect',()=>{

})?

**Comment by darrachequesne** [comment]
For future readers:

On the server-side:
- reduce the value of [`pingInterval`](https://socket.io/docs/v3/server-initialization/#pingInterval) (default: 25s) and [`pingTimeout`](https://socket.io/docs/v3/server-initialization/#pingTimeout) (default: 5s), so that unclean disconnections are caught earlier

On the client-side:
- reduce the value of [`reconnectionDelay`](https://socket.io/docs/v3/client-initialization/#reconnectionDelay) (default: 1s), so that reconnection is quicker
- maybe enable [`rememberUpgrade`](https://socket.io/docs/v3/client-initialization/#rememberUpgrade) (default: false), so that the WebSocket connection is established right away
