### ISSUE TITLE
Reconnect seems as successful but it isn't actually

### ISSUE THREAD

**Issue by kirill-kostenetskyi** [socketio/socket.io#3424]
**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

For bug reports and feature requests for the **Swift client**, please open an issue [there](https://github.com/socketio/socket.io-client-swift).

For bug reports and feature requests for the **Java client**, please open an issue [there](https://github.com/socketio/socket.io-client-java).

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Something strange is going on when I using socket.io library via GCP load balancer.

I have only one node behind the load balancer.

Load balancer breaks off socket connection in 30 seconds after the user was connected to any socket. By default GCP set HTTP timeout to 30 seconds for any requests. 

Once the first disconnect happens in 30 seconds, socket.io on client side immediately reconnect to the socket and this look like all should be ok, once I lost connection due to google interruption the library restoring it without any error, BUT the main issue that after this reconnection I can't receive messages via socket anymore. Connect event on Node.JS side was triggering only one time after the first connection, then I don't see any logs related to new connection due to reconnection on the client side. Why ? Why I don't see any errors on UI side and I see successful connection while on the backend it doesn't exist anymore and socket stop works?

### Steps to reproduce (if the current behaviour is a bug)
I using room and this is how client side connections looks:

```
var socket = io.connect('https://load.balancer.host');
socket.emit('join', { conversationId: 'conversation1' });
socket.on("new_msg", function (data) {
      alert(JSON.stringify(data));
});
```
This how my backend handles this connection:
```

io.sockets.on("connection", (socket) => {
    socket.on("join", (data) => {
        socket.join(data.conversationId); // We are using room of socket io

        socket.on("disconnect", (data) => {
            socket.leave(data.conversationId);
            console.log("Got disconnect!");
        });
    });
});
```

### Expected behaviour

I expected to reconnect to the same socket properly

### Setup
- OS: any
- browser: any
- socket.io version: latest

**Comment by ccjon** [comment]
Google engineers told me that the reason out socketio connections were not working were bc the first request after protocol change contains an Upgrade http header which is not forwarded downstream. The docs specifically callout such requests as not handled. I don't know why... perhaps so that the LB can handled all the protocol switching:
https://cloud.google.com/load-balancing/docs/https/
"The load balancer blocks the request if any of the following are true: ...
...
The request contains an Upgrade header and the Upgrade header is not used to enable WebSocket connections.
....

This is a big issue for me since it means I have to create an alternative route for websocket traffic via apache which is a lot more maintenance.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
