### ISSUE TITLE
Cannot store io.to("room") in a variable

### ISSUE THREAD

**Issue by fangzhangmnm** [socketio/socket.io#3444]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

When I store a io.to object to a variable, and call the object, the message was sent to all the clients, not only the clients in the room.

### Steps to reproduce (if the current behaviour is a bug)
I store io.to  to a variable:
```
this.broadcaster=io.to(this.internalRoomName);
```
Then I call the variable again somewhere else:
```
this.broadcaster.emit("someevent","something")
```
the server broadcast the event to all the client, not only the clients in the room

### Expected behaviour
What I expected:
```
io.to(this.internalRoomName).emit("someevent","something")
```

### Setup
- OS: Win10
- browser: Chrome and Edge
- socket.io version: v2.1.1

**Comment by ralphpig** [comment]
This is expected behavior. 

When you call `io.to(roomId)`, `roomId` is only stored for the upcoming `emit()`, and then those rooms are reset during `emit()`. 

So `this.broadcaster  = io.to(this.internalRoomName)` returns the original, modified `io` instance, and once `this.broadcaster.emit(...)` is called once, the rooms you set with `.to(...)` are reset.

**Comment by zyf0330** [comment]
I don't think this behavior is a good design. And doc describes it ambiguous 
> Sets a modifier for a subsequent event emission that the event will only be broadcasted to clients that have joined the given room.

I think this sentence means this modifier works for following event emission.

**Comment by darrachequesne** [comment]
This was fixed by https://github.com/socketio/socket.io/commit/ac9e8ca6c71e00d4af45ee03f590fe56f3951186 and included in `socket.io@4.0.0`

Calling `io.to()` (or any other broadcast modifier) will now return an immutable instance:

```js
const operator1 = io.to("room1");
const operator2 = operator1.to("room2");
const operator3 = socket.broadcast;
const operator4 = socket.to("room3").to("room4");

operator1.emit(/* ... */); // only to clients in "room1"
operator2.emit(/* ... */); // to clients in "room1" or in "room2"
operator3.emit(/* ... */); // to all clients but the sender
operator4.emit(/* ... */); // to clients in "room3" or in "room4" but the sender
```

Documentation: https://socket.io/docs/v3/migrating-from-3-x-to-4-0/#io-to-is-now-immutable
