### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /^[object$/: Unterminated character class

### ISSUE THREAD

**Issue by FaizanZahid** [socketio/socket.io#3448]
### You want to:

* [x] report a *bug*

### Current behaviour

*What is actually happening?*

Getting this error when trying to access socket io chat,

Uncaught SyntaxError: Invalid regular expression: /^[object$/: Unterminated character class

![image](https://user-images.githubusercontent.com/9073066/58446851-aad01180-8145-11e9-8521-9716e0e4b93d.png)

![image](https://user-images.githubusercontent.com/9073066/58447036-65601400-8146-11e9-8666-7a0634179c50.png)

### Steps to reproduce (if the current behaviour is a bug)

Just open any page and try to access socket io.js cdn 

### Expected behaviour

*What is expected?*

IO object should be defined and socket io.js should have no errors

### Setup
- OS: Windows
- browser: Chrome
- socket.io version: Socket.IO v2.2.0 on client,  

Package json:
    "socket.io": "2.2.0",
    "socket.io-adapter": "~1.1.1",
    "socket.io-client": "2.2.0",

It works when i open the page in chrome incognito but doesn't work in normal browser session.

**Comment by SidneyNemzer** [comment]
It's been a few months so maybe you worked around this, but I wanted to update with some info I discovered today.

This error is not related to socket.io, rather it's a problem with debug. See https://github.com/visionmedia/debug/issues/288

Now you might be wondering, why did this error get thrown?

In my case, it was a number of things interacting...

1. I have webpack-define-plugin set up to replace `process.env.DEBUG` with a stringified object -- that means it's an object at runtime. (it was not intended to set the debug config, the app used the data for something else).
2. debug saves the content of `process.env.DEBUG` to localstorage. At runtime, it's an object so this means localstorage contains `[object Object]`.
3. *On the next load*, debug reads from localstorage first, and tries to interpret `[object Object]`. debug's namespace logic splits on whitespace and interprets as regex, so it ends up calling `new RegExp("[object")` which throws an error as invalid regex.

In my case, the fix was to use a variable other than `process.env.DEBUG` to inject the data the app needs.

It works in incognito because localstorage is blank on the first load, but I suspect you'd get the same error if you reload the page.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
