### ISSUE TITLE
cant connect to socket io after scaling

### ISSUE THREAD

**Issue by CalmAndCoDe** [socketio/socket.io#3473]
## i cant connect to my socket io server after scalling

hello, i recently used socket io with redis for sharing the socket session between multiple instances,
it works well with the one instance but when i scale it to two or more it gets in the reconnection loop 
and it cant connect,

any help would be appreciated

**Comment by CalmAndCoDe** [comment]
it can be solved with sticky sessions routing but i want to figure out if any better solution are around.
thanks

**Comment by knoxcard** [comment]
do u have multiple servers?
are u just running one server with multiple app instances?

**Comment by CalmAndCoDe** [comment]
hello, yes i'm running express with the horizontal scaling in production, its not in release mode but i want to just tested out how it works and i deployed it in some cloud hosting.
also i tried to find which kind of LB they use but they didn't mentioned it. i assume they use Nginx with PM2 .

**Comment by knoxcard** [comment]
Use NGINX in front of your app and run PM2 in cluster mode.  Use Redis for your sessions, connect-redis. (https://www.npmjs.com/package/connect-redis)

Then install https://github.com/socketio/socket.io-redis

**Comment by CalmAndCoDe** [comment]
i use it but its not working as i mentioned in first comment

**Comment by baltar** [comment]
Using redis enables the socket.io instances in the different workers to communicate with each other, so that e.g. a message to a room finds its way to all clients in that room, regardless which worker they’re connected to.

But you still need sticky sessions for the connections themselves, whether implemented via the node module or an external node balancer (when using pm2 in cluster mode, the latter is the only option, because the pm2 process itself is the master). That’s because the socket.io handshake uses multiple consecutive connections, which all have to go to the same endpoint (worker) to succeed.

**Comment by CalmAndCoDe** [comment]
@knoxcard hi, thanks for your help but i solve it, it wasn't the issue with the socket io the problem was the client lib that i used.
