### ISSUE TITLE
memory leak if compression is enabled, on payload bigger than 25kb (or less too, if is converted into string)

### ISSUE THREAD

**Issue by shadowofsoul** [socketio/socket.io#3595]
# You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

If you pass a payload (string or binary) of more than 25kb, you get not only 1000x latency, but also an infinite memory leak. Looks like sender objects are not "dequequed".
### Steps to reproduce (if the current behaviour is a bug)

![screenshot-heap-snapshot](https://user-images.githubusercontent.com/375696/81115494-2d3a8700-8efa-11ea-9548-c8c5f1e6da21.jpg)

[Here](https://github.com/ipsilondev/socket.io-fiddle) is the fiddle to reproduce the case, including memory heap snapshot. Just run server.js and then client.js with Node.js.

### Expected behaviour

Not to have a memory leak
### Setup
- OS: Linux Ubuntu 19.10
- browser: Server version, nodejs
- socket.io version: 2.3.0
- NodeJS: v12.15.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

I have been digging the engine.io & Websocket code. I know for a fact, that the [dequeue function at sender.js](https://github.com/websockets/ws/blob/master/lib/sender.js#L352) is not called and that generates the memory leak. Like that function works on the premise of the `_deflating` prop, made me think that disabling compression would help (and it did). In the example i provide, can also be observed that passing a less than 25kb payload but as string, has the same result. Unfortunately, i don't have the time to dig more into an unknown codebase for now, if this is not fixed in the future, i'll look at it again in more detail to help as much as i can.

**Comment by darrachequesne** [comment]
For future readers:

I think the memory leak was due to the fact that packets are added to the queue faster than what `zlib` can compress.

If you replace the delay [here](https://github.com/ipsilondev/socket.io-fiddle/blob/db11f71c9e57b9243f0a753acd5c20e4eb6145fa/client.js#L13) with a more sane value like `10 ms` (instead of `0.3 ms`), then the queue gets properly emptied.

Disabling compression (which is now the default) or increasing the `concurrencyLimit` (see ws [options](https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketserveroptions-callback)) should fix the issue.

Related: https://github.com/websockets/ws/issues/1202

Please reopen if needed.
