### ISSUE TITLE
Server-side callbacks not a feature when sending to specific clients via SocketID?

### ISSUE THREAD

**Issue by Nathan1258** [socketio/socket.io#3619]
I'm opening another issue regarding the issue that was open way back in 2014, link to find it is [here](https://github.com/socketio/socket.io/issues/1444).

I find it really weird how this isn't a feature? Why can we perform client-side callbacks but not server-side callbacks?

I've seen solutions of people making their own callbacks but I'd need it so multiple instances of this code can be executed and sent all in one go rather than break it up in different emit functions and tracking what goes where with separate IDs.

I have this product that sits at a users home connected to their network. When they're outside their network, I'd like them to be able to access said product anywhere in the world with an internet connection securely. When my app needs data (that is only stored on the product at home) it goes through these steps:

 1. App sends request to server that it wants data from their product sitting at home
 2. Server get's request and sends a message down to their product via socket.io
 3. Product receives request and fetches the data (that's stored locally) and returns it back to the server (the callback)
 4. Server receives the data sent by the callback and sends it back to the users App.

Now I know with socket.io you can do callbacks client side, but why not server side callbacks?

Currently, with the code I have now I get the error `Callbacks are not supported when broadcasting`:

Server-side code (Nodejs):

    app.get('/hueapi/lights', verifyToken, (req,res) => {
      const bridgeIDFromApp = req.header('bridgeID');
      const socketID = socketRefDic[bridgeIDFromApp]['socketID'];
      io.to(socketID).emit('getAllLights', function(data){
          res.send(data); // The callback function that shows the data given by the python client
      });
    });

Client-side code (python):

    def getAllLights(data):
        lightData = requests.get('http://localhost:4000/lights/')
        return lightData

Is there a way/method around this, I find it silly how server-side callbacks aren't supported, or am I just doing something wrong?

**Comment by Nathan1258** [comment]
I am sending a message to specific clients - not broadcasting in my eyes. So I am not sure why this isn't a feature within sending data to specific sockets via their ID?

**Comment by thexeos** [comment]
For v3 and v4, you can get the `Socket` object by calling `io.sockets.sockets.get(socketID)`.
However, this will not work with adapters other than in-memory adapter (e.g., `socket.io-redis`).

Your best bet, in that case, is to create a custom listener (on each individual socket, or as a middleware) and have it check for events with a given name (e.g., getAllLightsResponse). Once the response is received, it now needs to be forwarded to the server that is expecting it. You can use `Emitter.serverSideEmit()` from https://github.com/socketio/socket.io-redis-emitter to create a custom handler that will invoke your desired code.

Something like this:

```javascript
const responseHandlerList = {}
function handleCustomResponseLocally (idFromClient, responsePayload) {
  if (responseHandlerList[idFromClient]) {
    responseHandlerList[idFromClient](responsePayload)
    delete responseHandlerList[idFromClient]
    return true
  }
  return false
}

// Emit event
const uniqueId = generateRandomId()
io.to(socketId).emit('name', payload, uniqueId)
responseHandlerList[uniqueId] = (responsePayload) => {
  // Handle response here. All scope variable are available.
}

// Listen for response from client
socket.on('nameResponse', (idFromClient, responsePayload) => {
  if (!handleCustomResponseLocally(idFromClient, responsePayload)) {
    emitter.serverSideEmit('handleCustomResponse', idFromClient, responsePayload)
  }
})

// Listen for cross-server events
io.on('handleCustomResponse', handleCustomResponseLocally)
```

Note, however, that this lacks exception handling, and will leak memory over time. It is possible that `responseHandlerList[uniqueId]` will never be invoked, for example because the client never sent a response, but the function will remain in memory. To mitigate, you will need to keep a list of `uniqueId`s related to each `socketId`, and then listen for `leave-room` events from the adapter, and when `socketId` leaves its own room (room id === socket id), you can clean up the callbacks.

```javascript
io.of('/').adapter.on('leave-room', (roomId, socketId) => {
  if (roomId === socketId) {
    for (const uniqueId of uniqueIdRegistry[socketId]) {
      delete responseHandlerList[uniqueId]
    }
  }
})
```

**Comment by thexeos** [comment]
@darrachequesne do you think this can be added to the roadmap? Support multi-server callbacks, and by extension support callbacks when broadcasting. This would require non-breaking changes to Adapter and to Server.

**Comment by darrachequesne** [comment]
@thexeos thanks for the heads-up, that's indeed an interesting feature, let's add it to the roadmap :+1:

**Comment by starzou** [comment]
@thexeos @darrachequesne How is this Progress?

**Comment by gaetansenn** [comment]
Is there any news about emit to specific sockets with io-redis ?

**Comment by darrachequesne** [comment]
@gaetansenn broadcasting with acknowledgements was added in version `4.5.0`:

```js
io.timeout(10000).emit("some-event", (err, responses) => {
  if (err) {
    // some clients did not acknowledge the event in the given delay
  } else {
    console.log(responses); // one response per client
  }
});
```

Reference: https://socket.io/docs/v4/server-api/#serveremiteventname-args
