### ISSUE TITLE
Server.on doesn't have documentation

### ISSUE THREAD

**Issue by SG5** [socketio/socket.io#3631]
### You want to:

* [x] report a *bug*

### Current behaviour

Documentation has many code exaples with `on` method
```javascript
io.on('connect', (socket) => {
  // ...
});
```
but I can't find documentation for `on` method itself

### Expected behaviour

Documentation should have `on` method in `Server API`

**Comment by ocke** [comment]
This so much. The documentation is horribly inconsistent.

- Is it `server` or `io`? Since it's the same, stick to one, and don't switch between them. This is very confusing.
- Is it `namespace` or `nsp`?
- Why are all the `server` apis undocumented? *Almost all examples* in the docs use undocumented apis 😱.
- Why are both `connect` and `connection` used in examples? What is the difference? (there is none)
- What is the difference between `server.on`, `namespace.on` and `socket.on`?
- What are the arguments to the `.on` callback? `(data)` or `(arg1, arg2, arg2)` or `(data, callback)`? How do I know which one to use? Why is `data` an instance of `Namespace`, for `server.on` and `namespace.on`, but not for `socket.on`?

If one were to use `socket.io` in a document way, one would have trouble setting it up, and that baffles me. Even better, as far as I know, it's not possible (`server` and `namespace` don't have have `.on`, so can't use that)

**Comment by darrachequesne** [comment]
This should be fixed now: https://socket.io/docs/v4/server-api/
