### ISSUE TITLE
How to use this function

### ISSUE THREAD

**Issue by jonalan7** [socketio/socket.io#3663]
How to use the io.in function 

`io.to(socketId).emit('message');`

through the front-end.

**Comment by aljaxus** [comment]
You have the docs for this.
https://socket.io/docs/v3/client-api/index.html#socket-emit-eventName-%E2%80%A6args-ack

You also disregarded the notice you had in the issue template;

**Note**: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)


Please just RTFM and close this issue.

**Comment by jonalan7** [comment]
OK! thank you!

**Comment by darrachequesne** [comment]
@jonalan7 you can only broadcast on the server-side, there's no such concept on the client-side. I will update the documentation to make it clearer.

**Comment by aljaxus** [comment]
Yeah looking back at it, the reply I posted above wasn't really kind, I'm sorry, @jonalan7 

To make up for it, if you haven't "RTFM" yet :stuck_out_tongue: ...

You can not emit a payload to a specific socket from client side, because your client only knows about one socket connection, the one that it has established with the server. If you want to sent some data from one client to all clients, you have to emit a specific event with the payload from the client to server, and then the server handles that event with a handler which then emits that data payload to all other sockets.
