### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by willyprayogo26** [socketio/socket.io#3740]
Why error after migrate from v2.2.0 to v2.4.0 ???
`Error during WebSocket handshake: Unexpected response code: 400`

**Comment by darrachequesne** [comment]
Hi! It might be linked to the CORS update. Did you check the release notes [here](https://github.com/socketio/socket.io/releases/tag/2.4.0)?

**Comment by willyprayogo26** [comment]
OK, I will check it. Thanks

**Comment by Dav-v** [comment]
Hi, we also encountered the same error yesterday, indeed it was linked to CORS. We updated socket.io from 2.3 to 2.4, and suddenly we had an `error 400: Bad request`. After [fixing CORS](https://socket.io/blog/socket-io-2-4-0/) everything worked fine.
One interesting thing: by coincidence we had `transports` set to only `['websocket']`, so it took a while to figure out that the problem was CORS: if the pooling fallback is enabled it is displayed on the console an error of the type `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3030/socket.io/?EIO=3&transport=polling&t=NROEP-d. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).` so it is easy to understand that the problem are missing CORS headers. But if you have only the websocket transport enabled, a generic `error 400: Bad request` is raised. I don't know if it would be possible to have a more descriptive error to point users in the right direction even if they are using only websocket trasport. Cheers

**Comment by willyprayogo26** [comment]
> Hi, we also encountered the same error yesterday, indeed it was linked to CORS. We updated socket.io from 2.3 to 2.4, and suddenly we had an `error 400: Bad request`. After [fixing CORS](https://socket.io/blog/socket-io-2-4-0/) everything worked fine.
> One interesting thing: by coincidence we had `transports` set to only `['websocket']`, so it took a while to figure out that the problem was CORS: if the pooling fallback is enabled it is displayed on the console of the browser an error of the type `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3030/socket.io/?EIO=3&transport=polling&t=NROEP-d. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).` , so it is easy to understand that the problem are missing CORS headers. But if you have only the websocket transport enabled, a generic `error 400: Bad request` is raised. I don't know if it would be possible to have a more descriptive error to point users in the right direction even if they are using only the websocket trasport. Cheers

Thanks for the information :+1:

**Comment by darrachequesne** [comment]
The change included in `socket.io@2.4.0` was reverted in `socket.io@2.4.1`: https://github.com/socketio/socket.io/releases/tag/2.4.1
