### ISSUE TITLE
Memory leak on 3.1.1

### ISSUE THREAD

**Issue by einsqing** [socketio/socket.io#3815]
Often disconnected, connected, memory consumption is increasing

**Comment by darrachequesne** [comment]
Hi! We'll need **a lot** more details in order to be able to help you:

- which version of Socket.IO server/client are you using?
- does it concern the server / the client / both?
- how are you detecting the memory leak? By comparing several heap snapshosts?

Could you please provide the code you are using? Thanks!

**Comment by einsqing** [comment]
server 3.1.1，client 3.1.1。According to the memory usage of docker container，More and more memory。Setting perMessageDeflate to false is much better, but the memory is still growing
