### ISSUE TITLE
socket.to(foobar).broadcast is broken in 4.0.0

### ISSUE THREAD

**Issue by Oasiris** [socketio/socket.io#3830]
This is my first-ever GitHub bug report, so please be gentle.

**Describe the bug**
In 3.x.x, calling `socket.to('myRoomId').broadcast` returned a BroadcastOperator.

In 4.0.0, calling `socket.to('myRoomId').broadcast` returns `undefined`.

This goes unmentioned in ["Migrating from 3.x to 4.0"](https://socket.io/docs/v3/migrating-from-3-x-to-4-0/).

**To Reproduce**

Socket.IO server version: `4.0.0`

*Server*

```js
const server = require('http').Server(app)
const io = require('socket.io')(server)

io.on("connection", (socket) => {
  socket.on('join-room', (roomId, userId) => {
    socket.to(roomId).broadcast.emit('user-connected', userId)
    // -> Exception thrown: "cannot get emit of undefined"
    
    console.log(socket.to(roomId).broadcast)
    // -> undefined
  })
});
```

Socket.IO client version: `4.0.0` or `3.1.1`

*Client*

```js
const socket = io('/')

const peerId = /* ... */

socket.emit('join-room', roomId, peerId)

socket.on("user-connected", (userId) => {
  console.log(`Connected: ${userId}`);
});
```

**Expected behavior**
Either:

1. The server-side code block `socket.to(roomId).broadcast` should be treated as `socket.broadcast.to(roomId)`. In other words, it should be BroadcastOperator and not `undefined`. Or:
2. This should be listed as a breaking change in ["Migrating from 3.x to 4.0"](https://socket.io/docs/v3/migrating-from-3-x-to-4-0/).

**Platform:**
 - OS: Mac OS Catalina

**Additional context**
While the syntax `socket.io(roomId).broadcast` is admittedly funky compared to `socket.broadcast.to(roomId)`, my project uses the former syntax because I saw it in [a YouTube video that has >300,000 views](https://youtu.be/DvlyzDZDEq4?t=838). So there must be many other users whose projects use this syntax.

**Comment by darrachequesne** [comment]
That's the first unintended breaking change of v4, congratulations! :smile: 

In fact, in 3.x.x, calling `socket.to('myRoomId').broadcast` would return the Socket instance itself ([here](https://github.com/socketio/socket.io/blob/3.1.2/lib/socket.ts#L511-L514)). The rooms and broadcast flags were tracked as internal properties of the Socket instance, which was problematic in some cases.

That being said, the `broadcast` in `socket.io(roomId).broadcast` was indeed useless (and is now deprecated), since the `to(roomId)` already put the Socket instance in broadcast mode:

```js
socket.broadcast.emit(); // to all clients but the current socket
socket.to(roomId).emit(); // to all clients in room "roomId" but the current socket
```

I'll update the migration guide accordingly.

**Comment by darrachequesne** [comment]
Added here: https://socket.io/docs/v3/migrating-from-3-x-to-4-0/#Known-migration-issues

Thanks for the heads-up! :+1:
