### ISSUE TITLE
Unable to access class methods and properties inside event listener

### ISSUE THREAD

**Issue by M1T0zd** [socketio/socket.io#3849]
**Describe the bug**
When an event is set in the constructor of a class with another method of the class as a listener, accessing methods or properties of the class inside that method (used as the listener) results in an error:
`TypeError: Cannot read private member #socket from an object whose class did not declare it`

**To Reproduce**
I have distilled the problem to just this using socket.io-mock
Do `npm install socket.io-mock` and run this code.
```js
class User {
	#socket;

	constructor(socket) {
		this.#socket = socket;
		this.#login();
	}

	#login() {
		this.#socket.on("logout", this.logout);
		console.log("User has logged in!");
	}

	logout() {
		// When `logout` is called by the logout event set in `#login`, this next line will result in an error.
		this.#socket.removeListener("logout", this.logout);
		console.log("User has logged out!");
	}
}

// Simulate socket
const SocketMock = require('socket.io-mock');
var socket = new SocketMock();

// Create and login user
var user = new User(socket);

// Logout user client-side (but fail trying).
socket.socketClient.emit("logout");

/*
	Replacing line 10 with `this.#socket.on("logout", () => this.logout())` or
	`this.#socket.on("logout", () => this.logout.bind(this))` would solve the error somehow,
	but would render line 16 useless as it would now not refer to the same symbol.
*/
```
socket.io-mock version: 1.3.1

**Expected behavior**
Being able to access the methods and properties of a class in a method passed to an event in that class' constructor.

**Additional context**
I have some ideas as to why this is happening, but I'm not sure. Is this intended behavior? I would like to be able to remove the listener of the event set in the constructor, inside its listener. I feel like this is a natural way of doing it.

**Comment by darrachequesne** [comment]
Hi! This does not seem directly related to Socket.IO, it does not work with a plain EventEmitter:

```js
const { EventEmitter } = require("events")

class User {
  #socket;

  constructor(socket) {
    this.#socket = socket;
    this.login();
  }

  login() {
    this.#socket.on("logout", this.logout);
    console.log("User has logged in!");
  }

  logout() {
    // When `logout` is called by the logout event set in `#login`, this next line will result in an error.
    this.#socket.removeListener("logout", this.logout);
    console.log("User has logged out!");
  }
}

const socket = new EventEmitter();
const user = new User(socket);

socket.emit("logout"); // TypeError: Cannot read private member #socket from an object whose class did not declare it
```

Could you please check?

**Comment by M1T0zd** [comment]
Ah, I see. You're right. I guess I should take this to Node.js directly then.
Thanks for the quick response!

**Comment by sploders101** [comment]
This is actually a javascript language quirk, not something `EventEmitter` has screwed up on. Javascript classes are based on prototypal inheritance, contrary to other object-oriented languages. The `this` object is bound to whatever object the function was called from, so by passing your class's function straight onto the `on` function, you aren't allowing it to keep its association with the class. Try passing `this.logout.bind(this)` into the function. the `bind` function (present as a property on all functions) "binds" a `this` value to the function, such that it cannot be changed by method in which it is called. [(See here)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind)

As an example, `animal.makeNoise` and `computer.makeNoise` can refer to the same function, but it will be different depending on which method you use to call it. In the first example, `makeNoise` will receive `animal` as the `this` variable, and in the second, it will receive `computer`. [(See here)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this)

You're passing it to `EventEmitter` as a standalone value, meaning eventEmitter will receive it in a variable like `callback`. It will then run `callback(data)` to dispatch the event, and because there is nothing before the function call, `this` will be `undefined`.
