### ISSUE TITLE
Not running properly in Replit.com

### ISSUE THREAD

**Issue by idkwhattoputhere121** [socketio/socket.io#3934]
Literally does not run.
npm start does not work
npm test is continuously doing useless file checks...

**Comment by Veggieoskibroski** [comment]
Have you manually installed socket.io using the shell? In the shell area, type npm install socket.io

Also, if this isn't an issue with socket.io, but with npm on replit, you should check the replit help

**Comment by AllRacs** [comment]
@idkwhattoputhere121 does your `package.json` look like this? In order to run `npm start` the "main" has to be defined as well as the "scripts.start".
```
{
    "main": "index.js",
    "scripts": {
        "start": "node index.js",
        "...": "..."
    },
    "...": "..."
}
```

You should install the packages through the shell as commented by @Veggieoskibroski, I just created a NodeJS project in replit.com, followed the [Get Started guide](https://socket.io/get-started/chat) and I haven't had any issue to run socket.io.

These are the steps I followed:

1. Create Node project
2. shell: `npm init -y`
3. shell: `npm install express`
4. shell: `npm install socket.io`
5. in `package.json`: define the "start" script in "scripts"
6. follow the Get Started guide from above to create a simple chat project
7. shell: `npm start`
8. Done :)

You can check my replit code [here](https://replit.com/@allracs/socketio-test) if you want.

**Comment by darrachequesne** [comment]
I've updated the link to an actual example: https://replit.com/@socketio/socketio-minimal-example

Thanks for reporting the issue :+1:
