### ISSUE TITLE
Dev Console got `http://localhost:3000/socket.io/socket.io.js is being assigned a //# sourceMappingURL, but already has one`

### ISSUE THREAD

**Issue by xreider** [socketio/socket.io#3958]
**Describe the bug**
Dev Console got `http://localhost:3000/socket.io/socket.io.js is being assigned a //# sourceMappingURL, but already has one`

**To Reproduce**

Socket.IO server version:"socket.io": "^4.1.2",

*Server*

```js
const { io } = require('./app', {
  // allowEIO3: true, // false by default
});
io.on('connection', socket => {
  console.log('IO connected');
});
```

Socket.IO server version:"socket.io": "^4.1.2",

*Client*

client side pug
```
script(src='/socket.io/socket.io.js')
script.
  const socket = io();
  //- socket.on('hello', function (data) {
  //-   console.log(data);
  //- });
script(src='/bundles/bundle.js') // generated by web pack
```

**Comment by darrachequesne** [comment]
I guess that's because we have both:

- the sourcemap field in the bundle

https://github.com/socketio/socket.io/blob/1633150b2bcdebd3c39dc37f7329e84e9951a15e/client-dist/socket.io.min.js#L7

- and the `X-SourceMap` header

https://github.com/socketio/socket.io/blob/1633150b2bcdebd3c39dc37f7329e84e9951a15e/lib/index.ts#L521

I think we could remove the header now.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io/commit/a4dffc6527f412d51a786ae5bf2e9080fe1ca63c, included in `socket.io@4.1.3`.

Thanks!
