### ISSUE TITLE
webrtc

### ISSUE THREAD

**Issue by JACKJKL** [socketio/socket.io#4107]
Will webrtc support be added in the future?

**Comment by abhiraj-kale** [comment]
i think its already possible. This may help
https://acidtango.com/thelemoncrunch/how-to-implement-a-video-conference-with-webrtc-and-node/

**Comment by darrachequesne** [comment]
@JACKJKL that's an interesting idea! Could you please explain what the benefits of webRTC would be over plain WebSocket?

**Comment by abhiraj-kale** [comment]
> @JACKJKL that's an interesting idea! Could you please explain what the benefits of webRTC would be over plain WebSocket?
When we use WebRTC the communication happens directly from client to client instead of passing through the server(like in the case of socket.io). Also the overhead is less when using webrtc over socket.io, so when we want high quality data transmission like video calls in minimum time then we use webrtc.

**Comment by JACKJKL** [comment]
> i think its already possible. This may help https://acidtango.com/thelemoncrunch/how-to-implement-a-video-conference-with-webrtc-and-node/

Very good thanks

**Comment by LeoDog896** [comment]
Note that this shouldn't be mixed up -- socket.io can *transmit* WebRTC data such as ICE candidates, offers, answers, and the like, but it can't use WebRTC's data channels as a transport AFAIK.
