### ISSUE TITLE
Add wildcard support for events

### ISSUE THREAD

**Issue by edmellum** [socketio/socket.io#434]
It would be great if you could use a wildcard to capture all events. For example:

```
client.on("*", function(data) {

}
```

**Comment by MaffooBristol** [comment]
I ended up using @NathanGRomano's [socketio-events](https://www.npmjs.com/package/socket.io-events) module; it seems the most transparent method (by using middleware) and works quite nicely for me. But :+1: for getting this into core!

**Comment by NathanGRomano** [comment]
Thanks Matt!  I have been swamped but I hope to have a weekend to make some
improvements

Sent from my iPhone

On Jan 6, 2015, at 8:30 AM, Matt Fletcher <notifications@github.com> wrote:

I ended up using @NathanGRomano <https://github.com/NathanGRomano>'s
socketio-events <https://www.npmjs.com/package/socket.io-events> module; it
seems the most transparent method (by using middleware) and works quite
nicely for me. But [image: :+1:] for getting this into core!

—
Reply to this email directly or view it on GitHub
<https://github.com/Automattic/socket.io/issues/434#issuecomment-68864750>.

**Comment by xenyou** [comment]
+1

**Comment by leonardovillela** [comment]
+ 1

**Comment by vsdigitall** [comment]
++++++

**Comment by EddieOne** [comment]
+1 would be useful for debugging.

**Comment by johnmanko** [comment]
If it's a matter of someone just working on this, I'd like to give it a shot.  I'll need some to learn the socket.io codebase, and I'll probably spend some time looking at other such implementations.  What are your thoughts on regex patterns?  Too slow?  Of course, I'm not going to waste my time if it's not something that would be considered for a merge (I don't care if my implementation is rejected, but if there is no interest then why bother, right?).  Will a maintainer please advise?

**Comment by NathanGRomano** [comment]
I wrote a library socket.io-events.  I've been swamped with work and need
to touch it again.  I'd like to support the acknowledgments with it

**Comment by elennaro** [comment]
+1

**Comment by Tectract** [comment]
+1 this issue is going on 5 years old. Why hasn't wildcard support been added in, again?

**Comment by ChadTaljaardt** [comment]
+1

**Comment by andrewda** [comment]
+1

**Comment by DutchKev** [comment]
+1

**Comment by WellDone2094** [comment]
+1

**Comment by jimutt** [comment]
+1

**Comment by Darker** [comment]
+666

**Comment by Michael77** [comment]
+1

**Comment by MaffooBristol** [comment]
Guys, seriously. Everyone wants this feature- I think they get it. Let's all stop with the plus-ones, please? I'd rather get an update email when there's some actual progress with the issue.

**Comment by rauchg** [comment]
That said, it's useful to know that many people are interested.
I think ideally GitHub should have a voting system?

>

**Comment by carpii** [comment]
A voting system would be great, but doesnt seem likely to happen anytime soon.

I guess the problem is a solution has been posted many times now, but scrolls out of view because of all the +1 comments.

The socketio-wildcard module has been working well for me (admittedly I haven't updated to latest node yet). 
It would be useful if someone could explain why this lib is not suitable?

**Comment by MaffooBristol** [comment]
Yeah, [socketio-wildcard](https://www.npmjs.com/package/socketio-wildcard) works perfectly well, but it's still an extra dependency that is so simple that it would be nice to be introduced into core and just end this whole issue thread once and for all. Also it removes any room for confusion as to which is the best external module to use (often similarly named). Also agree that it would be good if GitHub had a voting system, if only there was a way we could vote on it...!

**Comment by n2liquid** [comment]
I may be dumb, but I have no clue how to set up socketio-wildcard with IO client objects. This should seriously, *seriously* be included in the core. If socket.io's maintainers don't want to do it, someone should just fork this project and we could all move there, because this is just ridiculous and I have honestly have zero trust in socket.io now.

I understand that maintainers don't have to accept every proposal, but this? This just totally baffles me. Way to go.

**Comment by rauchg** [comment]
@n2liquid it's not as clear that this should be in core, but the discussion is welcome. For example, no other Node event emitter behaves this way, even though a discussion was had there as well when.

**Comment by carpii** [comment]
@rauchg 

> it's not as clear that this should be in core, but the discussion is welcome

Could we have a discussion about then? i can understand your point that this sort of emitter is not necessarily common in the node world, but it depends what you are trying to achieve.

It seems clear that many users of socket.io are really stumbling without this feature being in core, and it seems reasonable to expect that it should be. 
Is the idea to simply adhere to convention, or provide a really useful library?

Or to put it another way, what are the arguments to NOT provide this feature in socket.io?  
Even if the implementation is not 'textbook correct', it would result in a standard way to handle these issues, rather than people having to resort to lots of different libraries and methods to work around what is essentially a commonly requested limitation.

**Comment by Michael77** [comment]
@rauchg I think a cool way to implement this would to have a `socket.use(function(data,next){..})` function that catches all events on the socket, and is passed a next() function that passes control from the catchall to subsequent catchalls or default event handlers.

This is how I am using socket.io right now because I needed a way to limit the amount of events coming in per/minute, which I believe is a common use case. Thanks for reading my 2 cents.

**Comment by n2liquid** [comment]
I like @Michael77's solution the most. It doesn't touch the event emitter interfaces or implementation and even allows for more things than we're asking here (e.g. @Michael77's message throttling implementation and who knows what else).

I know there's a middleware / use function in socket.io, but it's not usable on the client library, and I'm not sure if it serves this same purpose.

**Comment by rauchg** [comment]
@carpii there are always great reasons to *not* support something: adding complexity, reducing familiarity. This feature checks off both.

I like the `socket.use` idea a lot, on top of which one could easily implement the wildcard extension on the client.

**Comment by rauchg** [comment]
Thanks @carpii @Michael77 @n2liquid for your feedback on this btw.

**Comment by n2liquid** [comment]
@rauchg, I'm sorry I said those bad things about socket.io. I was having a bad day. Thank you for this project; it may not be perfect, but it sure is very useful.

**Comment by rauchg** [comment]
@n2liquid *all* feedback is welcome – thank you (and to @hden for that quick fix on [socket.io-wildcard](https://github.com/hden/socketio-wildcard)).

**Comment by akotlar** [comment]
scoketio-wildcard seems like a perfectly valid solution. I found myself also wanting to get the event name in callback, so that I could wrap the socket listener and propagate events through the wrapper, rather than directly exposing the socket to the rest of my application. My understanding is that this would require Event Emitter 2 if I wanted to do this with a wildcard. Is this just something silly to do, better to directly expose the socket? Something based on listening for 'newListener' in the wrapper (but don't know how to trigger on socket event, only how to register the socket event based on the calling functions registering a new event in the wrapper)? Anyone else interested in being able to access the event name within the callback?

**Comment by hden** [comment]
@akotlar The event name is available in the callback if you are using scoketio-wildcard.

**Comment by akotlar** [comment]
Ah, thanks!

**Comment by alexey-sh** [comment]
how it's going?
+1 for `on("*", function () {` for both client and server

**Comment by emin93** [comment]
+1 all the way

**Comment by hden** [comment]
@alexey-sh @emin93  If you would kindly read the document from https://github.com/hden/socketio-wildcard, yes it's possible to do so for both client and server.

**Comment by emin93** [comment]
@hden Thanks and yes i saw that and i'm already using it. But it's an extra dependency and nothing speaks against integrating it directly into Socket.IO core, that's why it gets a +1 from me.

**Comment by mkhahani** [comment]
It can be handled in the app logic using one event name for all events:

```
socket.emit('public-event', {'type': 'login', ...});
socket.emit('public-event', {'type': 'logout', ...});
```

**Comment by juanpaulo** [comment]
+1 even though issue is closed.

**Comment by crobinson42** [comment]
+💯 bang!

**Comment by lizjulien** [comment]
+1 !!!!

**Comment by darrachequesne** [comment]
Please use [`socket.use`](https://github.com/socketio/socket.io#socketusefnfunctionsocket).

**Comment by carpii** [comment]
Is there a way to hook into engine.io's PING/PONG mechanism using socket.use() ?

I am having an issue where many users are losing connection, and despite extensive logging on server, it just says they disconnected due to Ping Timeout.

I'd like to log the PING/PONG packets, but it seems socket.use() can only hook into the high level user-event messages, and not engine.io's underlying protocol

**Comment by freeman3s** [comment]
+1

**Comment by gtk2k** [comment]
+1

**Comment by bolajipemipo** [comment]
+1 since 2011? They ain't doing it. :(

**Comment by darrachequesne** [comment]
Again, `socket.use` was added for that matter: https://socket.io/docs/server-api/#socket-use-fn

**Comment by errorx666** [comment]
@darrachequesne I don't see how a method on the server-side helps with this request (which is for the client).

**Comment by nigelbpeck** [comment]
Any more on this? Since socket.use is only for the server, why is this ticket closed?

**Comment by bor8** [comment]
I don't understand `socket.use`. How to replace

```
// Server
io.in('room1').emit('backend', data_out);
io.in('room1').emit('frontend', data_out);
```

with something like

```
// Server
io.in('room1').emit('*end', data_out);  // not working code - proper regex would be nice
```

or

```
// Client
socket.on('*end', async function(data){  // not working code - proper regex would be nice
```

**Comment by nomi9995** [comment]
can i use subscribe like this `socket.on('posting/*'`
where I wanna get all posting like this
`posting/1`
`posting/2`
`posting/3`

**Comment by darrachequesne** [comment]
@nomi9995 no, but implementing this should be quite straightforward:

```js
socket.onAny((eventName, ...args) => {
  if (/posting\/.*/.test(eventName)) {
    // ...
  }
});
```

Reference: https://socket.io/docs/v4/listening-to-events/#socketonanylistener
