### ISSUE TITLE
Security issue [CVE-2022-2421] CWE-89 - Score 10.0

### ISSUE THREAD

**Issue by phyr0s** [socketio/socket.io#4509]
**Describe the bug**
Security Issue 

Auditjs output:

[1037/1198] - pkg:npm/socket.io@4.5.3 - 1 vulnerability found!
  Vulnerability Title:  [CVE-2022-2421] CWE-89: Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')
  ID:  CVE-2022-2421
  Description:  Due to improper type validation in attachment parsing the Socket.io js library, it is possible to overwrite the _placeholder object which allows an attacker to place references to functions at arbitrary places in the resulting query object.
  CVSS Score:  10
  CVSS Vector:  CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H
  CVE:  CVE-2022-2421
  Reference:  https://ossindex.sonatype.org/vulnerability/CVE-2022-2421?component-type=npm&component-name=socket.io&utm_source=auditjs&utm_medium=integration&utm_content=4.0.37
  
  
  Sonar output:
  
  socket.io@4.5.2 has vulnerabilities: * [CVE-2022-2421] CWE-89: Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection') - Score 10.0 - https://ossindex.sonatype.org/vulnerability/CVE-2022-2421?component-type=npm&component-name=socket.io&utm_source=auditjs&utm_medium=integration&utm_content=4.0.22

**Comment by darrachequesne** [comment]
Thanks for the heads-up. I'll try to make the advisory a bit clearer.

Related: https://github.com/socketio/socket.io-parser/commit/b5d0cb7dc56a0601a09b056beaeeb0e43b160050

**Comment by neomedeiros** [comment]
Please, any updates on this?

Should we expect any fix soon?

**Comment by darrachequesne** [comment]
@neomedeiros this is already fixed by https://github.com/socketio/socket.io-parser/commit/b5d0cb7dc56a0601a09b056beaeeb0e43b160050, included in `socket.io-parser@4.2.1`.

:warning: For all future readers :warning: 

The issue does not seem realistically exploitable, but please upgrade to a safe version as soon as possible.

You can use `npm audit fix` to bump the version of the `socket.io-parser` package.

You can find more details here: https://github.com/advisories/GHSA-qm95-pgcg-qqfq

**Comment by ejodet** [comment]
Hello @darrachequesne - I can not run npm audit fix right now.
Any ETA for a new version of socket.io that will include socket.io-parser@4.2.1?

**Comment by darrachequesne** [comment]
@ejodet the latest version of `socket.io` includes `socket.io-parser@~4.2.0`, so running `npm audit fix` or `npm update socket.io-parser` should be sufficient. Isn't that the case?

**Comment by ejodet** [comment]
Hello @darrachequesne 
https://security.snyk.io/vuln/SNYK-JS-SOCKETIOPARSER-3091012
claims:
Upgrade socket.io-parser to version 4.0.5, 4.2.1 or higher.

However, the latest version of socket-io includes 4.2.0 - supposedly not sufficient to fix Snyk vuln.
Hence me asking.

(I managed to fix my problem)
Thanks

**Comment by llaakso** [comment]
"The issue does not seem realistically exploitable" - this is classified as critical so more analysis would be appreciated if this indeed is exploitable or not.

Secondly, if that really is something to concern, we're stuck at socket.io v.2, patch - or hotfix - for that is needed too.

**Comment by darrachequesne** [comment]
@llaakso I tried to improve the advisory here: https://github.com/github/advisory-database/pull/810

Here is the updated analysis:

Assuming the server properly validates the format of the input sent by the clients (by following the "never trust user input" philosophy), there is no way for a malicious user to make the server crash.

Example of values that could be sent by a malicious user:

- a number that is out of bounds

Sample packet: `451-["hello",{"_placeholder":true,"num":10}]`

```js
io.on("connection", (socket) => {
  socket.on("hello", (val) => {
    // val is `undefined`
  });
});
```

- a value that is not a number, like `undefined`

Sample packet: `451-["hello",{"_placeholder":true,"num":undefined}]`

```js
io.on("connection", (socket) => {
  socket.on("hello", (val) => {
    // val is `undefined`
  });
});
```

- a string that is part of the prototype of `Array`, like "push"

Sample packet: `451-["hello",{"_placeholder":true,"num":"push"}]`

```js
io.on("connection", (socket) => {
  socket.on("hello", (val) => {
    // val is a reference to the "push" function
  });
});
```

- a string that is part of the prototype of `Object`, like "hasOwnProperty"

Sample packet: `451-["hello",{"_placeholder":true,"num":"hasOwnProperty"}]`

```js
io.on("connection", (socket) => {
  socket.on("hello", (val) => {
    // val is a reference to the "hasOwnProperty" function
  });
});
```

The fix was also backported to v2:

- https://github.com/socketio/socket.io-parser/commit/04d23cecafe1b859fb03e0cbf6ba3b74dff56d14
- https://github.com/socketio/socket.io-parser/commit/fb21e422fc193b34347395a33e0f625bebc09983

**Comment by joacimsvensson** [comment]
> `socket.io-parser`

This doesn't help if your organization has a package management system which supports blocking downloads of packages with severe vulnerabilities. Since 4.5.3 uses the vulnerable 4.2.0 parser, it is blocked from download long before anyone has a change to manually update the parser to 4.2.1.

That is why a new version of socket.io that uses the 4.2.1-parser is needed.

**Comment by Havanero** [comment]
![image](https://user-images.githubusercontent.com/5183091/202421124-a5b4c5d5-410a-4879-8097-1f4e2e2f49fe.png)
 socket.io@4.5.3
─ $ ▶ npm update socket.io-parser

up to date, audited 956 packages in 2s

118 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
---
Anyidea why AWS still complains?

**Comment by darrachequesne** [comment]
Here we go: https://github.com/socketio/socket.io/releases/tag/4.5.4
