### ISSUE TITLE
Acknowledgements behave incorrectly when emitting to a single socket with io.to(socketId).emit()

### ISSUE THREAD

**Issue by sgraffite** [socketio/socket.io#4583]
In the case where you want to emit from the server side to the client side with an acknowledgement using the style io.to(socketId).emit() will always receive an acknowledgement back with a response of empty array.  This is true even if the event is not listened for on the client side.  This is also true if an invalid socket ID is provided.  Adding a timeout() does not change the behavior.

Socket.IO server version: `4.5.4`

*Server example that does not work*
```
io.to(socketId).emit('event-name', data, (err, response) => {
          if (err) {
            console.log(`${eventName} err`, err);
          } else {
            console.log(`${eventName} response`, response);
          }
        });
```

*Server example that does work*
```
const socket = io.sockets.sockets.get(socketId);
socket.emit('event-name', data, (err, response) => {
          if (err) {
            console.log(`${eventName} err`, err);
          } else {
            console.log(`${eventName} response`, response);
          }
        });
```

**Expected behavior**
The callback would end up in the if(err) code block since it is never acknowledged client side.

**Comment by darrachequesne** [comment]
Hi! The `timeout()` method is mandatory when broadcasting with an acknowledgement:

```js
socket.emit('event-name', "direct", (response) => {
  console.log(`event-name response`, response);
});

socket.timeout(1000).emit('event-name', "direct with timeout", (err, response) => {
  if (err) {
    console.log(`event-name err`, err);
  } else {
    console.log(`event-name response`, response);
  }
});

io.timeout(1000).to(socket.id).emit('event-name2', "room", (err, response) => {
  if (err) {
    console.log(`event-name err`, err);
  } else {
    console.log(`event-name response`, response); // response is an array with one single element
  }
});
```

Reference: https://socket.io/docs/v4/broadcasting-events/#with-acknowledgements

**Comment by sgraffite** [comment]
I mentioned in the original message that adding a timeout() does not change the behavior.

Also it works with no timeout if you emit from the socket with an acknowledgement as in my original example.

Should the behavior ever be automatically acknowledging?

**Comment by elmcremotebridge** [comment]
I notice with a timeout sometime the callback will work and sometime results come back null because the remote client has not had enough time to respond. would be nice if we could ```await``` for response

**Comment by darrachequesne** [comment]
For future readers:

The `emitWithAck()` method was added in version 4.6.0:

```js
try {
  const responses = await io.timeout(10000).emitWithAck("some-event");
  console.log(responses); // one response per client
} catch (e) {
  // some clients did not acknowledge the event in the given delay
}
```

Reference: https://socket.io/docs/v4/server-api/#serveremitwithackeventname-args

**Comment by kent0318** [comment]
Hi, I just had the same issue. I somehow found a workaround by io.sockets.sockets.get(socketId).emit(). Not sure why it works though.

**Comment by barroudjo** [comment]
Here's the real answer for those that stumble upon this problem, the documentation is somewhat lacking in that respect:
`io.to(socketId).timeout(5000).emit('event-name', data, (err, response) => {...}`  is actually a broadcast to potentially multiple clients. Hence this documentation actually applies: https://socket.io/blog/socket-io-4-5-0/#multiple-acknowledgements-when-broadcasting.

`response` will be an array in which each element will be a response from a client. @sgraffite you were getting an empty array when no clients were connected, or when the socket id was incorrect because that corresponds to no response, which is correct since there are no clients available to respond in those cases !

So it all makes sense (and I've confirmed it works as expected when there are clients the `io.to(socketIdOrRoomId)` corresponds to) , the documentation is just not explicit enought about that.
