### ISSUE TITLE
Setting retries to Infinity causes emit to break but volatile.emit continues to work

### ISSUE THREAD

**Issue by mgarf** [socketio/socket.io#4793]
**Describe the bug**
Setting retries to Infinity causes emit to stop working. When you use volatile.emit it does work.

**To Reproduce**

  io(process.env.URL, {
        transports: ['websocket'],
        autoConnect: false,
        retries: Infinity,
  });

Please fill the following code example:

Socket.IO server version: `4.7.2`

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.on("disconnect", () => {
    console.log(`disconnect ${socket.id}`);
  });
});
```

Socket.IO client version: `4.7.1`

*Client*

```js
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", {
        transports: ['websocket'],
        autoConnect: false,
        retries: Infinity,
  });

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
```

**Expected behavior**
Either an error due to invalid configuration, but at minimum volatile.emit not working (made it very difficult to debug why only some messages were coming through). Or Emit working with Infinity retries

**Comment by eunji624** [comment]
I'm developing a real-time chat service using NestJS and socket.io. It operates smoothly in a local environment, but when deployed with Kubernetes, GCP, load balancers, and Docker, I encounter either short or long cycles of disconnection depending on the configuration. The issue arises after a disconnection, as messages are still being stored in the database. Here's what happens:

After an initial disconnection, messages of connections and disconnections are repeatedly logged in the console. It seems to function this way due to socket.io's built-in features, but there's a part that I don't understand. If the connection is lost, message transmission should be impossible, yet messages are still being stored in Redis. However, the functionality to render these messages to the client does not work. Moreover, events designed to send alerts to the client are operating correctly. When the 'send' button is clicked by the client, the message is successfully sent to the server, and then the server triggers an event to send an alert back to the client, which also executes and displays successfully.

Therefore, features for preventing spam and filtering prohibited words are working, but when a user inputs a normal message, it does not appear on the screen.

Why does it operate this way, where some functions work despite the connection being lost, while others do not? I'm very curious about this aspect. Is there anyone who can help?

**Comment by darrachequesne** [comment]
I think this can be closed now. Please reopen if needed.
