### ISSUE TITLE
TypeError: callback is not a function in examples/basic-crud-application

### ISSUE THREAD

**Issue by pjonczyk** [socketio/socket.io#4806]
**Describe the bug**
The example does not work as intended. There is a TypeError on the server side. When called, the server cannot fullfill the request but crashes with
`\socket.io\examples\basic-crud-application\server\lib\todo-management\todo.handlers.ts:153
        callback({
        ^
TypeError: callback is not a function`

**To Reproduce**
Install the server side of the basic-crud-application as described in the readMe. `npm install`
Start the server side as described in the readMe. `npm start`
Connect to `localhost:3000` via Postman.
Send `todo:list` as event in Postman.
Error visible in server log.
Socket.IO server version: `^4.0.1`

Code: See code from your example in `app-ts`, `events.ts` and `todo-management\todo.handlers.ts`

The error is thrown in `todo-management\todo.handlers.ts`

**Expected behavior**
No error and response from server on the provided event.

**Platform:**
 - Device: PC
 - OS: Windows 10

**Comment by darrachequesne** [comment]
For future readers:

That's because the `todo:list` event expects an acknowledgement callback, to return the list of todo objects.

Example in JS:

```js
socket.emit("todo:list", ({ error, data }) => {
  // ...
});
```

I'm not sure this can be achieved with the Postman client.

Reference: https://github.com/socketio/socket.io/blob/fd99f2e15fef0e17ae9e3849c92ef0ca616a5919/examples/basic-crud-application/server/lib/todo-management/todo.handlers.ts#L151-L161
