### ISSUE TITLE
 Possibly incorrect code in the documentation

### ISSUE THREAD

**Issue by citizenofgreatsiberia** [socketio/socket.io#5191]
**Description of the problem:**
In the Socket.IO documentation for step 7, `await` is used outside of an asynchronous function, which causes an error.

**Link to the documentation:**
[Socket.IO Tutorial - Step 7](https://socket.io/docs/v4/tutorial/step-7)

**Code example:**
```javascript
const db = await open({
    filename: 'chat.db',
    driver: sqlite3.Database
});
```
**Suggestion for correction:**
Wrap the code in an asynchronous function:
```javascript
async function initializeDatabase() {
    const db = await open({
        filename: 'chat.db',
        driver: sqlite3.Database
    });
    // remaining code
}
```

**Comment by darrachequesne** [comment]
Hi! Top-level await is available since Node.js v14, that's why we used it in the tutorial. Are you using an earlier release?

That being said, we indeed do not suggest a minimum version, maybe we could add a note for this.

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

**Comment by citizenofgreatsiberia** [comment]
Hello! My mistake was probably that I didn't save the changes to the package.json file after adding "type": "module". As a result, I was getting an error about incorrect use of await at the top level. Sorry for my mistake.

**Comment by darrachequesne** [comment]
Sure, no problem! Have a great day.
