### ISSUE TITLE
why does socket.io uses websocket connection and xhr polling parallel?

### ISSUE THREAD

**Issue by bodokaiser** [socketio/socket.io#991]
Hi,

I am new to socket.io and am wondering why socket.io keeps up two connections:
1. Websocket
2. XHR polling

at the same time?

Isn't this a bit stupid?

**Comment by goliatone** [comment]
Has this issue been solved? I'm seeing something similar, but before I start digging deep I wanted to do a quick search... comments?

**Comment by nevercast** [comment]
The code has changed a fair bit since I last commented on this issue. It's unlikely it's the same bug. I can't see to find the line that I suspected was causing the issue last time.

My socket.io code is currently blocked by a bug engine.io-client so I've not used s.io for a few months now so can't say for certain if this is still an issue.

**Comment by mattffc** [comment]
@nevercast your comment about wss working but ws not was totally right in my case. Thanks for pointing it out I've been searching for this issue for over a week. Found that somehow any ws connection on my network was being blocked but wss worked fine.

**Comment by mattffc** [comment]
This website is great: http://websocketstest.com/ it tells you which ports are able to run websockets on any given network. Recommend checking this before getting too involved in websocket debugging.

**Comment by gowthamyaal** [comment]
i have an issue with socket io but not sure where i am wrong.
![image](https://user-images.githubusercontent.com/42035439/43952722-5f82b73a-9cb4-11e8-9ab7-c719f0c328d2.png)

the above image show that it works fine in local but the below image is captured while attempting in AWS environment.

![image](https://user-images.githubusercontent.com/42035439/43952855-c20bfe2a-9cb4-11e8-8418-0434d0cc6748.png)

**Comment by Abbasi393** [comment]
> i have an issue with socket io but not sure where i am wrong.
> ![image](https://user-images.githubusercontent.com/42035439/43952722-5f82b73a-9cb4-11e8-9ab7-c719f0c328d2.png)
> 
> the above image show that it works fine in local but the below image is captured while attempting in AWS environment.
> 
> ![image](https://user-images.githubusercontent.com/42035439/43956416-c02b6200-9cc1-11e8-82b3-281b07abb2df.png)

facing same problem

**Comment by Rsquare-14** [comment]
Hello , I am using socket.io. The backend is placed at a different folder (./quagmire-api). The frontend is making two type of requests. 
1. websocket connection
2. XHR requests.
I have configured the routes so that all the requests are diverted through /quagmire-api. All the xhr requests are working fine except the websocket connection. I am not getting a 101 changing protocols message when requesting connection. You can see the below image.
![image](https://user-images.githubusercontent.com/96003203/167997059-f3565b2d-bd43-4fb4-97f7-0a462a132d1b.png)

The xhr requests are working fine as shown in below image.
![image](https://user-images.githubusercontent.com/96003203/167997130-a57679ba-b8be-4147-a88b-8d6db62a18d8.png)

I am thinking that backend is not able to respond to the ws connection request. Can anyone help me on this.
I am sharing a similar question on stackoverflow for more info.
[https://stackoverflow.com/questions/72185922/issue-regarding-web-socket-in-socket-io-back-end-placed-in-different-folder](url)
