### ISSUE TITLE
Duplicate events

### ISSUE THREAD

**Issue by smileart** [socketio/socket.io#997]
Here I create primitive example of server with socket.io with such stuff:
- socket.io > 0.9.9

``` bash
├─┬ socket.io@0.9.9
│ ├── policyfile@0.0.4
│ ├─┬ redis@0.7.2
│ │ └── hiredis@0.1.14
│ └─┬ socket.io-client@0.9.9
│   ├─┬ active-x-obfuscator@0.0.1
│   │ └── zeparser@0.0.5
│   ├── uglify-js@1.2.5
│   ├─┬ ws@0.4.21
│   │ ├── commander@0.6.1
│   │ ├── options@0.0.3
│   │ └── tinycolor@0.0.1
│   └── xmlhttprequest@1.4.2
└──────────────────── ●
```
- node -v   > v0.8.7
- https://github.com/Balloon/elephant.io

_on x86_64 Linux_: 

Distributor ID:  Ubuntu
Description:       Ubuntu 12.04.1 LTS
Release:       12.04
Codename:      precise
Kernel:              3.2.0-29-generic
GCC version:   4.6 (x86_64-linux-gnu)

``` javascript

var io = require('socket.io').listen(1717);

io.sockets.on('connection', function (socket) {
  socket.on('ping', function (data){
      console.log(data);
  });

  socket.on('message', function(data){
      console.log(data);
  });
});
```

And PHP-client like this:

``` php
#!/usr/bin/php -q

<?php
error_reporting(E_ALL);
require(dirname(__FILE__).'ElephantIO/Client.php');

$elephant = new ElephantIO\Client('http://localhost:1717');
$elephant->init(false);

$elephant->emit('ping', array('test' => 'Hello World!'), '');
// $elephant->send(ElephantIO\Client::TYPE_MESSAGE, null, null, 'Hello World!');
```

Here is the log of that server:

``` bash
   info  - socket.io started
   debug - client authorized
   info  - handshake authorized KAZbMECxcHQBIgTXynHr
   debug - setting request GET /socket.io/1/websocket/KAZbMECxcHQBIgTXynHr
   debug - set heartbeat interval for client KAZbMECxcHQBIgTXynHr
   debug - client authorized for 
   debug - websocket writing 1::
   debug - websocket received data packet 1:::
   debug - websocket writing 1::
   debug - websocket received data packet 3:::Hello World!
Hello World! 
Hello World!
```

So, every time php-client sends **one** message or emits event, it's duplicated on the server side :(

**Comment by RadekHavelka** [comment]
I have the same problem on linux, when using PHP to submit one event, its been fired twice ... the issue is closed without any further explanation or solution, why ?

**Comment by peteruithoven** [comment]
Make sure you check the debug output, see http://socket.io/docs/logging-and-debugging/ This could rule out that it's in your own code.

**Comment by RadekHavelka** [comment]
I run very basic example from docs, no fancy code (yet), and I am experiencing the double events being fired. I will try to log/debug the output and will see whats going on.

**Comment by elemenofi** [comment]
I have this issue too and I am using the code from the website's example.

**Comment by philpill** [comment]
Was this ever fixed? I think I'm seeing the same issue with a very simple ping-pong script.

**Comment by ladislav-mizenko** [comment]
Same issue here using Flask-SocketIO 1.1 on server

**Comment by smileart** [comment]
Just can't believe since August 2012 this issue wasn't properly addressed and people still continue reporting it. The splendors and miseries of open source. 😮

**Comment by EduardJS** [comment]
You guys found a fix for this issue since I see it as closed ? I'm still experiencing the same issue... with a simple ExpressJS / Socket.io app. I connect the one user, broadcasting it to other users,
restarting the server, connecting the same user, the broadcast is being received twice on the second restart. Three times after the third restart, and so on.

[http://i.imgur.com/TUJr3yf.png](http://i.imgur.com/TUJr3yf.png)

I have 2 clients connected with some debugging and I'm broadcasting two events uppon connection and one on disconnect.

Upon connection:
1 - broadcast to all users ( aside the current one ) the "member_joined" event.
2. broadcast to socket.id ( current user ) the "member_list" event so I can show what users are already online.

Upon disconnect:
1. broadcast to all users aside current one, the `member_left` event so others are aware of it.

Now that I have two clients connected, the events are triggered as many times as the server has been restarted. Look at that image.

My thought was .. to try and disconnect the client from all rooms or something upon server being restarted. Is that possible ?

**Comment by islam9** [comment]
Problem is about where you call you message event " socket.on('message') " must not be inside connection scope in your client js file .

`io.sockets.on('connection', function (socket) {
});`

--> This is out of the scope ....  
`socket.on('message', function(data){
      console.log(data);
});`

**Comment by EduardJS** [comment]
@islam9 You have no idea what you're talking about.

What he wrote in his example is perfectly correct. I have already fixed the problem and this is not related by far with `socket.io` , nor `nodejs`, that's why they **cannot** / **wont** fix it.

When you attach event handlers to a `socket` there is no way in hell you're going to get that `socket object` if you are not inside the `connection` like this. 

`io.on('connection, function( socket ){ });`

Think of that `socket` param as being the object in which the client's socket is saved. Each of them will be one of those sockets to which you'll have to attach some events in order to listen to them disconnecting, pinging, etc.

The problem is in the client itself, and it's related to your clients reconnecting to your socket server.
Therefore it has nothing to do with `socket.io`. When the server is not reachable for any reason, the events your `client` attaches upon `connection` will be listened to again ( and again, as many times your socket.io reconnects successfully ).

Therefore, my fix, since I am working with simple javascript as my own "client" interface, I'm checking if there is already a handler like the one I'm trying to attach, before attaching it upon reconnection, and since reconnection implies the `connect` event to be triggered again, your `client` will attach `two or more` callbacks to the same event.

![image](https://cloud.githubusercontent.com/assets/7712869/15317585/6d5ac312-1c22-11e6-833b-fba89a844ff2.png)

Check out my issue it has more images to explain https://github.com/socketio/socket.io/issues/2529

**Comment by islam9** [comment]
@eduarjs I mentioned that its the client file , and not related to the nodeJS ,
Also , am am indicating that issue is regarding duplicate msg not connection .

**Comment by JCMais** [comment]
@EduardJS why not just use ``.once``?

**Comment by EduardJS** [comment]
@JCMais 'socket.once' will remove the event after it has been fired. Therefore it is not usable.

What you need here is to make sure you attach the events only once, no matter how many re-connections you have. 
You do not want to remove them after they fire first time ( which is what .once does ) as they can fire multiple times. Think of receiving messages for that matter. You want to receive all messages, not just one and then unbind the event.

**Comment by JCMais** [comment]
@EduardJS yes, I saw my mistake on using ``.once`` yesterday, forgot to edit my comment.

Basically it's because most (myself included) people add all events inside the ``connection`` callback, which causes that behavior.

**Comment by msenevir** [comment]
Just ran into this issue as well. 

Originally, I was attaching listeners on the client like this:

```
socket.on('connect', () => {
    socket
        .emit('sendAuthCredentials', { ... })
        .on('user joined', () => { ... })
        .on('user left', () => { ... })
})
```

But @EduardJS explains it very well:
> What you need here is to make sure you attach the events only once, no matter how many re-connections you have

My solution was to take the listeners out of the `connect` callback, and only leave my auth check (which I *do* want to run on every connection attempt):
```
socket.on('connect', () => {
    socket.emit('sendAuthCredentials', { ... })
})

socket
    .on('user joined', () => { ... })
    .on('user left', () => { ... })
```

**Comment by HardlyMirage** [comment]
Any explanation to why this issue is marked closed?

**Comment by msenevir** [comment]
I didn't close the issue, so I can't say.

That said, my issue was a problem with how I was attaching listeners, not so much a bug with socket.io

**Comment by mishaetaya** [comment]
Hi @EduardJS - thank you for your explanation, it really helps understand what is happening. But I don't fully understand your fix.  I posted a question on stackoverflow with the details of my code - https://stackoverflow.com/questions/44909405/socket-io-server-emits-multiple-times  

would it be possible for you to take a look and tell me what I'm doing wrong?  I don't fully follow where to implement this code:

    for ( var event in this.events[ type ] )
        if ( !this.socket._callbacks[ '$' + event ] )
            this.socket.on( event, this.events[ type ][ event ] );

thank you!

best,
Mike
